/* 
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.paint;

/**
Builder class for javafx.scene.paint.Stop
@see javafx.scene.paint.Stop
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public final class StopBuilder implements javafx.util.Builder<javafx.scene.paint.Stop> {
    protected StopBuilder() {
    }
    
    /** Creates a new instance of StopBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.paint.StopBuilder create() {
        return new javafx.scene.paint.StopBuilder();
    }
    
    private javafx.scene.paint.Color color = javafx.scene.paint.Color.BLACK;
    /**
    Set the value of the {@link javafx.scene.paint.Stop#getColor() color} property for the instance constructed by this builder.
    */
    public javafx.scene.paint.StopBuilder color(javafx.scene.paint.Color x) {
        this.color = x;
        return this;
    }
    
    private double offset;
    /**
    Set the value of the {@link javafx.scene.paint.Stop#getOffset() offset} property for the instance constructed by this builder.
    */
    public javafx.scene.paint.StopBuilder offset(double x) {
        this.offset = x;
        return this;
    }
    
    /**
    Make an instance of {@link javafx.scene.paint.Stop} based on the properties set on this builder.
    */
    public javafx.scene.paint.Stop build() {
        javafx.scene.paint.Stop x = new javafx.scene.paint.Stop(this.offset, this.color);
        return x;
    }
}
