/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.Separator
@see javafx.scene.control.Separator
@deprecated This class is deprecated and will be removed in the next version
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class SeparatorBuilder<B extends javafx.scene.control.SeparatorBuilder<B>> extends javafx.scene.control.ControlBuilder<B> implements javafx.util.Builder<javafx.scene.control.Separator> {
    protected SeparatorBuilder() {
    }
    
    /** Creates a new instance of SeparatorBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.SeparatorBuilder<?> create() {
        return new javafx.scene.control.SeparatorBuilder();
    }
    
    private int __set;
    public void applyTo(javafx.scene.control.Separator x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setHalignment(this.halignment);
        if ((set & (1 << 1)) != 0) x.setOrientation(this.orientation);
        if ((set & (1 << 2)) != 0) x.setValignment(this.valignment);
    }
    
    private javafx.geometry.HPos halignment;
    /**
    Set the value of the {@link javafx.scene.control.Separator#getHalignment() halignment} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B halignment(javafx.geometry.HPos x) {
        this.halignment = x;
        __set |= 1 << 0;
        return (B) this;
    }
    
    private javafx.geometry.Orientation orientation;
    /**
    Set the value of the {@link javafx.scene.control.Separator#getOrientation() orientation} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B orientation(javafx.geometry.Orientation x) {
        this.orientation = x;
        __set |= 1 << 1;
        return (B) this;
    }
    
    private javafx.geometry.VPos valignment;
    /**
    Set the value of the {@link javafx.scene.control.Separator#getValignment() valignment} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B valignment(javafx.geometry.VPos x) {
        this.valignment = x;
        __set |= 1 << 2;
        return (B) this;
    }
    
    /**
    Make an instance of {@link javafx.scene.control.Separator} based on the properties set on this builder.
    */
    public javafx.scene.control.Separator build() {
        javafx.scene.control.Separator x = new javafx.scene.control.Separator();
        applyTo(x);
        return x;
    }
}
