#!/bin/bash
#
# use as a pipe to rename an jdk 9  module path to the jdk 8 module path
#

case "`uname`" in
    Darwin*) platform="macosx";;
    CYGWIN*) platform="windows" ; PATHSEP=";";;
    Windows_NT*) platform="mks" ; PATHSEP=";";;
    Linux*)  platform="linux";;
    SunOS*)  platform="solaris";;
esac

if [ "X$platform" = "Xmacosx" ]
then
sed  -E \
 -e '/^(diff |--- |\+\+\+ )/s,modules/jdk.packager/,modules/fxpackager/,g' \
 -e '/^(diff |--- |\+\+\+ )/s,modules/jdk.packager.services/,modules/fxpackagerservices/,g' \
 -e '/^(diff |--- |\+\+\+ )/s,extensions/,modules/extensions/,g' \
 \
 -e '/^(diff |--- |\+\+\+ )/s,modules/javafx.([a-z]*)/src/test/java/test/,modules/\1/src/test/java/,g' \
 -e '/^(diff |--- |\+\+\+ )/s,tests/system/src/test/java/test/,tests/system/src/test/java/,g' \
 \
 -e '/^(diff |--- |\+\+\+ )/s,modules/javafx.(base|graphics|controls|swing|media|web|fxml|swt|jmx)/,modules/\1/,g' 

else
sed \
 -e '/^\(diff \|--- \|+++ \)/s,modules/jdk.packager/,modules/fxpackager/,g' \
 -e '/^\(diff \|--- \|+++ \)/s,modules/jdk.packager.services/,modules/fxpackagerservices/,g' \
 -e '/^\(diff \|--- \|+++ \)/s,extensions/,modules/extensions/,g' \
 \
 -e '/^\(diff \|--- \|+++ \)/s,modules/javafx.\(base\|graphics\|controls\|swing\|media\|web\|fxml\|swt\|jmx\)/src/test/java/test/,modules/\1/src/test/java/,g' \
 -e '/^\(diff \|--- \|+++ \)/s,tests/system/src/test/java/test/,tests/system/src/test/java/,g' \
 \
 -e '/^\(diff \|--- \|+++ \)/s,modules/javafx.\(base\|graphics\|controls\|swing\|media\|web\|fxml\|swt\|jmx\)/,modules/\1/,g' 

fi

exit 0
