/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.embed.swt;

/**
Builder class for javafx.embed.swt.CustomTransfer
@see javafx.embed.swt.CustomTransfer
@deprecated This class is deprecated and will be removed in the next version
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class CustomTransferBuilder<B extends javafx.embed.swt.CustomTransferBuilder<B>> implements javafx.util.Builder<javafx.embed.swt.CustomTransfer> {
    protected CustomTransferBuilder() {
    }
    
    /** Creates a new instance of CustomTransferBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.embed.swt.CustomTransferBuilder<?> create() {
        return new javafx.embed.swt.CustomTransferBuilder();
    }
    
    private java.lang.String mime;
    /**
    Set the value of the {@link javafx.embed.swt.CustomTransfer#getMime() mime} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B mime(java.lang.String x) {
        this.mime = x;
        return (B) this;
    }
    
    private java.lang.String name;
    /**
    Set the value of the {@link javafx.embed.swt.CustomTransfer#getName() name} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B name(java.lang.String x) {
        this.name = x;
        return (B) this;
    }
    
    /**
    Make an instance of {@link javafx.embed.swt.CustomTransfer} based on the properties set on this builder.
    */
    public javafx.embed.swt.CustomTransfer build() {
        javafx.embed.swt.CustomTransfer x = new javafx.embed.swt.CustomTransfer(this.name, this.mime);
        return x;
    }
}
