/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_CharacterData_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link CharacterDataImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class CharacterDataNative {

    private static final MethodHandle GET_DATA = WebKitNative.downcall("wkj_dom_CharacterData_getData",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_DATA = WebKitNative.downcall("wkj_dom_CharacterData_setData",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_LENGTH = WebKitNative.downcall("wkj_dom_CharacterData_getLength",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_PREVIOUS_ELEMENT_SIBLING = WebKitNative.downcall(
            "wkj_dom_CharacterData_getPreviousElementSibling", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_NEXT_ELEMENT_SIBLING = WebKitNative.downcall(
            "wkj_dom_CharacterData_getNextElementSibling", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SUBSTRING_DATA = WebKitNative.downcall("wkj_dom_CharacterData_substringData",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle APPEND_DATA = WebKitNative.downcall("wkj_dom_CharacterData_appendData",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle INSERT_DATA = WebKitNative.downcall("wkj_dom_CharacterData_insertData",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle DELETE_DATA = WebKitNative.downcall("wkj_dom_CharacterData_deleteData",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT));
    private static final MethodHandle REPLACE_DATA = WebKitNative.downcall("wkj_dom_CharacterData_replaceData",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle REMOVE = WebKitNative.downcall("wkj_dom_CharacterData_remove",
            FunctionDescriptor.ofVoid(JAVA_LONG));

    private CharacterDataNative() {
    }

    static String getData(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_DATA.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_DATA.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setData(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_DATA.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static int getLength(long peer) {
        try {
            return (int) GET_LENGTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getPreviousElementSibling(long peer) {
        try {
            return (long) GET_PREVIOUS_ELEMENT_SIBLING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getNextElementSibling(long peer) {
        try {
            return (long) GET_NEXT_ELEMENT_SIBLING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String substringData(long peer, int offset, int length) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) SUBSTRING_DATA.invokeExact(peer, offset, length, resultBuffer, DOMStringCodec.CAPACITY,
                        resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) SUBSTRING_DATA.invokeExact(peer, offset, length, resultBuffer, required,
                            resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            WebKitNative.checkException();
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void appendData(long peer, String data) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment dataSegment = WebKitNative.allocString(arena, data);
            try {
                APPEND_DATA.invokeExact(peer, dataSegment, WebKitNative.stringLength(data));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void insertData(long peer, int offset, String data) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment dataSegment = WebKitNative.allocString(arena, data);
            try {
                INSERT_DATA.invokeExact(peer, offset, dataSegment, WebKitNative.stringLength(data));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
    }

    static void deleteData(long peer, int offset, int length) {
        try {
            DELETE_DATA.invokeExact(peer, offset, length);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void replaceData(long peer, int offset, int length, String data) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment dataSegment = WebKitNative.allocString(arena, data);
            try {
                REPLACE_DATA.invokeExact(peer, offset, length, dataSegment, WebKitNative.stringLength(data));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
    }

    static void remove(long peer) {
        try {
            REMOVE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }
}
