/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_CSSStyleDeclaration_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link CSSStyleDeclarationImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class CSSStyleDeclarationNative {

    private static final MethodHandle DISPOSE = WebKitNative.downcall("wkj_dom_CSSStyleDeclaration_dispose",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle GET_CSS_TEXT = WebKitNative.downcall("wkj_dom_CSSStyleDeclaration_getCssText",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_CSS_TEXT = WebKitNative.downcall("wkj_dom_CSSStyleDeclaration_setCssText",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_LENGTH = WebKitNative.downcall("wkj_dom_CSSStyleDeclaration_getLength",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_PARENT_RULE = WebKitNative.downcall(
            "wkj_dom_CSSStyleDeclaration_getParentRule", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_PROPERTY_VALUE = WebKitNative.downcall(
            "wkj_dom_CSSStyleDeclaration_getPropertyValue",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_PROPERTY_CSS_VALUE = WebKitNative.downcall(
            "wkj_dom_CSSStyleDeclaration_getPropertyCSSValue",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle REMOVE_PROPERTY = WebKitNative.downcall(
            "wkj_dom_CSSStyleDeclaration_removeProperty",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_PROPERTY_PRIORITY = WebKitNative.downcall(
            "wkj_dom_CSSStyleDeclaration_getPropertyPriority",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_PROPERTY = WebKitNative.downcall("wkj_dom_CSSStyleDeclaration_setProperty",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle ITEM = WebKitNative.downcall("wkj_dom_CSSStyleDeclaration_item",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_PROPERTY_SHORTHAND = WebKitNative.downcall(
            "wkj_dom_CSSStyleDeclaration_getPropertyShorthand",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle IS_PROPERTY_IMPLICIT = WebKitNative.downcall(
            "wkj_dom_CSSStyleDeclaration_isPropertyImplicit",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT));

    private CSSStyleDeclarationNative() {
    }

    static void dispose(long peer) {
        try {
            DISPOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getCssText(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_CSS_TEXT.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_CSS_TEXT.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setCssText(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_CSS_TEXT.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static int getLength(long peer) {
        try {
            return (int) GET_LENGTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getParentRule(long peer) {
        try {
            return (long) GET_PARENT_RULE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getPropertyValue(long peer, String propertyName) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment propertyNameSegment = WebKitNative.allocString(arena, propertyName);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_PROPERTY_VALUE.invokeExact(peer, propertyNameSegment,
                        WebKitNative.stringLength(propertyName), resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_PROPERTY_VALUE.invokeExact(peer, propertyNameSegment,
                            WebKitNative.stringLength(propertyName), resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static long getPropertyCSSValue(long peer, String propertyName) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment propertyNameSegment = WebKitNative.allocString(arena, propertyName);
            try {
                result = (long) GET_PROPERTY_CSS_VALUE.invokeExact(peer, propertyNameSegment,
                        WebKitNative.stringLength(propertyName));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result;
    }

    static String removeProperty(long peer, String propertyName) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment propertyNameSegment = WebKitNative.allocString(arena, propertyName);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) REMOVE_PROPERTY.invokeExact(peer, propertyNameSegment,
                        WebKitNative.stringLength(propertyName), resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) REMOVE_PROPERTY.invokeExact(peer, propertyNameSegment,
                            WebKitNative.stringLength(propertyName), resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            WebKitNative.checkException();
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static String getPropertyPriority(long peer, String propertyName) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment propertyNameSegment = WebKitNative.allocString(arena, propertyName);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_PROPERTY_PRIORITY.invokeExact(peer, propertyNameSegment,
                        WebKitNative.stringLength(propertyName), resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_PROPERTY_PRIORITY.invokeExact(peer, propertyNameSegment,
                            WebKitNative.stringLength(propertyName), resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setProperty(long peer, String propertyName, String value, String priority) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment propertyNameSegment = WebKitNative.allocString(arena, propertyName);
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            MemorySegment prioritySegment = WebKitNative.allocString(arena, priority);
            try {
                SET_PROPERTY.invokeExact(peer, propertyNameSegment, WebKitNative.stringLength(propertyName),
                        valueSegment, WebKitNative.stringLength(value), prioritySegment,
                        WebKitNative.stringLength(priority));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
    }

    static String item(long peer, int index) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) ITEM.invokeExact(peer, index, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) ITEM.invokeExact(peer, index, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static String getPropertyShorthand(long peer, String propertyName) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment propertyNameSegment = WebKitNative.allocString(arena, propertyName);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_PROPERTY_SHORTHAND.invokeExact(peer, propertyNameSegment,
                        WebKitNative.stringLength(propertyName), resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_PROPERTY_SHORTHAND.invokeExact(peer, propertyNameSegment,
                            WebKitNative.stringLength(propertyName), resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static boolean isPropertyImplicit(long peer, String propertyName) {
        int result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment propertyNameSegment = WebKitNative.allocString(arena, propertyName);
            try {
                result = (int) IS_PROPERTY_IMPLICIT.invokeExact(peer, propertyNameSegment,
                        WebKitNative.stringLength(propertyName));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result != 0;
    }
}
