/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_DocumentFragment_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link DocumentFragmentImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class DocumentFragmentNative {

    private static final MethodHandle GET_CHILDREN = WebKitNative.downcall("wkj_dom_DocumentFragment_getChildren",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_FIRST_ELEMENT_CHILD = WebKitNative.downcall(
            "wkj_dom_DocumentFragment_getFirstElementChild", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_LAST_ELEMENT_CHILD = WebKitNative.downcall(
            "wkj_dom_DocumentFragment_getLastElementChild", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_CHILD_ELEMENT_COUNT = WebKitNative.downcall(
            "wkj_dom_DocumentFragment_getChildElementCount", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_ELEMENT_BY_ID = WebKitNative.downcall(
            "wkj_dom_DocumentFragment_getElementById", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle QUERY_SELECTOR = WebKitNative.downcall("wkj_dom_DocumentFragment_querySelector",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle QUERY_SELECTOR_ALL = WebKitNative.downcall(
            "wkj_dom_DocumentFragment_querySelectorAll",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));

    private DocumentFragmentNative() {
    }

    static long getChildren(long peer) {
        try {
            return (long) GET_CHILDREN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getFirstElementChild(long peer) {
        try {
            return (long) GET_FIRST_ELEMENT_CHILD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getLastElementChild(long peer) {
        try {
            return (long) GET_LAST_ELEMENT_CHILD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getChildElementCount(long peer) {
        try {
            return (int) GET_CHILD_ELEMENT_COUNT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getElementById(long peer, String elementId) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment elementIdSegment = WebKitNative.allocString(arena, elementId);
            try {
                result = (long) GET_ELEMENT_BY_ID.invokeExact(peer, elementIdSegment,
                        WebKitNative.stringLength(elementId));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result;
    }

    static long querySelector(long peer, String selectors) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment selectorsSegment = WebKitNative.allocString(arena, selectors);
            try {
                result = (long) QUERY_SELECTOR.invokeExact(peer, selectorsSegment,
                        WebKitNative.stringLength(selectors));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result;
    }

    static long querySelectorAll(long peer, String selectors) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment selectorsSegment = WebKitNative.allocString(arena, selectors);
            try {
                result = (long) QUERY_SELECTOR_ALL.invokeExact(peer, selectorsSegment,
                        WebKitNative.stringLength(selectors));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result;
    }
}
