/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import java.lang.foreign.MemorySegment;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;

/**
 * The caller-provided-buffer string protocol shared by every string-returning DOM downcall
 * (see {@code modules/javafx.web/FFM-ABI-CONTRACT.md} section 13). The library writes UTF-16 code
 * units into a buffer this side allocates and owns, so nothing is returned that could dangle and
 * there is no "valid until the next call" rule for a facade to get wrong.
 * <p>
 * Null and empty are distinguished on the way out, which several {@code org.w3c.dom} getters rely
 * on: {@link #NULL} is Java {@code null}, {@link #OK} with a zero length is {@code ""}. On the way
 * in they collapse, because that is what the JNI bindings did (contract section 11.1).
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl}. Do not edit; regenerate.
 */
final class DOMStringCodec {

    /** {@code WKJ_STR_OK}: {@code result_length} code units were written. */
    static final int OK = 0;

    /** {@code WKJ_STR_NULL}: the Java-visible value is {@code null}. */
    static final int NULL = 1;

    /** {@code WKJ_STR_OVERFLOW}: nothing was written; {@code result_length} is the capacity needed. */
    static final int OVERFLOW = 2;

    /**
     * The capacity, in UTF-16 code units, of the buffer a string getter offers on its first
     * attempt. Every attribute, tag name, URL and style property in the DOM fits; the
     * {@code innerHTML}, {@code outerHTML} and {@code textContent} shaped getters are the ones that
     * overflow, and they pay one extra downcall for an exactly sized buffer.
     */
    static final int CAPACITY = 256;

    private DOMStringCodec() {
    }

    /**
     * Turns a completed string call into its Java value.
     *
     * @param status the {@code WKJ_STR_*} status the call returned
     * @param buffer the buffer the call wrote into
     * @param length the segment the call wrote the code unit count into
     * @return the string, or {@code null} if the status is {@link #NULL}
     */
    static String decode(int status, MemorySegment buffer, MemorySegment length) {
        if (status == NULL) {
            return null;
        }
        if (status != OK) {
            // The caller has already grown the buffer to the size the library asked for, so a
            // second overflow means the two sides disagree about the protocol.
            throw new IllegalStateException("jfxwebkit returned string status " + status
                    + " for a buffer of the size it asked for");
        }
        int count = length.get(JAVA_INT, 0);
        if (count == 0) {
            return "";
        }
        char[] chars = new char[count];
        MemorySegment.copy(buffer, JAVA_CHAR, 0L, chars, 0, count);
        return new String(chars);
    }
}
