/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_DOUBLE;
import static java.lang.foreign.ValueLayout.JAVA_FLOAT;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_DOMWindow_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link DOMWindowImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class DOMWindowNative {

    private static final MethodHandle DISPOSE = WebKitNative.downcall("wkj_dom_DOMWindow_dispose",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle GET_FRAME_ELEMENT = WebKitNative.downcall("wkj_dom_DOMWindow_getFrameElement",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_OFFSCREEN_BUFFERING = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOffscreenBuffering", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_OUTER_HEIGHT = WebKitNative.downcall("wkj_dom_DOMWindow_getOuterHeight",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_OUTER_WIDTH = WebKitNative.downcall("wkj_dom_DOMWindow_getOuterWidth",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_INNER_HEIGHT = WebKitNative.downcall("wkj_dom_DOMWindow_getInnerHeight",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_INNER_WIDTH = WebKitNative.downcall("wkj_dom_DOMWindow_getInnerWidth",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SCREEN_X = WebKitNative.downcall("wkj_dom_DOMWindow_getScreenX",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SCREEN_Y = WebKitNative.downcall("wkj_dom_DOMWindow_getScreenY",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SCREEN_LEFT = WebKitNative.downcall("wkj_dom_DOMWindow_getScreenLeft",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SCREEN_TOP = WebKitNative.downcall("wkj_dom_DOMWindow_getScreenTop",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SCROLL_X = WebKitNative.downcall("wkj_dom_DOMWindow_getScrollX",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SCROLL_Y = WebKitNative.downcall("wkj_dom_DOMWindow_getScrollY",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_PAGE_X_OFFSET = WebKitNative.downcall("wkj_dom_DOMWindow_getPageXOffset",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_PAGE_Y_OFFSET = WebKitNative.downcall("wkj_dom_DOMWindow_getPageYOffset",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_CLOSED = WebKitNative.downcall("wkj_dom_DOMWindow_getClosed",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_LENGTH = WebKitNative.downcall("wkj_dom_DOMWindow_getLength",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_NAME = WebKitNative.downcall("wkj_dom_DOMWindow_getName",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_NAME = WebKitNative.downcall("wkj_dom_DOMWindow_setName",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_STATUS = WebKitNative.downcall("wkj_dom_DOMWindow_getStatus",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_STATUS = WebKitNative.downcall("wkj_dom_DOMWindow_setStatus",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_DEFAULT_STATUS = WebKitNative.downcall("wkj_dom_DOMWindow_getDefaultStatus",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_DEFAULT_STATUS = WebKitNative.downcall("wkj_dom_DOMWindow_setDefaultStatus",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_SELF = WebKitNative.downcall("wkj_dom_DOMWindow_getSelf",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_WINDOW = WebKitNative.downcall("wkj_dom_DOMWindow_getWindow",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_FRAMES = WebKitNative.downcall("wkj_dom_DOMWindow_getFrames",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_OPENER = WebKitNative.downcall("wkj_dom_DOMWindow_getOpener",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_PARENT = WebKitNative.downcall("wkj_dom_DOMWindow_getParent",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_TOP = WebKitNative.downcall("wkj_dom_DOMWindow_getTop",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_DOCUMENT_EX = WebKitNative.downcall("wkj_dom_DOMWindow_getDocumentEx",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_DEVICE_PIXEL_RATIO = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getDevicePixelRatio", FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_ONANIMATIONEND = WebKitNative.downcall("wkj_dom_DOMWindow_getOnanimationend",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONANIMATIONEND = WebKitNative.downcall("wkj_dom_DOMWindow_setOnanimationend",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONANIMATIONITERATION = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOnanimationiteration", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONANIMATIONITERATION = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOnanimationiteration", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONANIMATIONSTART = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOnanimationstart", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONANIMATIONSTART = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOnanimationstart", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONTRANSITIONEND = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOntransitionend", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONTRANSITIONEND = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOntransitionend", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWEBKITANIMATIONEND = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOnwebkitanimationend", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWEBKITANIMATIONEND = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOnwebkitanimationend", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWEBKITANIMATIONITERATION = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOnwebkitanimationiteration", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWEBKITANIMATIONITERATION = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOnwebkitanimationiteration", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWEBKITANIMATIONSTART = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOnwebkitanimationstart", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWEBKITANIMATIONSTART = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOnwebkitanimationstart", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWEBKITTRANSITIONEND = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOnwebkittransitionend", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWEBKITTRANSITIONEND = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOnwebkittransitionend", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONABORT = WebKitNative.downcall("wkj_dom_DOMWindow_getOnabort",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONABORT = WebKitNative.downcall("wkj_dom_DOMWindow_setOnabort",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONBLUR = WebKitNative.downcall("wkj_dom_DOMWindow_getOnblur",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBLUR = WebKitNative.downcall("wkj_dom_DOMWindow_setOnblur",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCANPLAY = WebKitNative.downcall("wkj_dom_DOMWindow_getOncanplay",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCANPLAY = WebKitNative.downcall("wkj_dom_DOMWindow_setOncanplay",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCANPLAYTHROUGH = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOncanplaythrough", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCANPLAYTHROUGH = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOncanplaythrough", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCHANGE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnchange",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCHANGE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnchange",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCLICK = WebKitNative.downcall("wkj_dom_DOMWindow_getOnclick",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCLICK = WebKitNative.downcall("wkj_dom_DOMWindow_setOnclick",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCONTEXTMENU = WebKitNative.downcall("wkj_dom_DOMWindow_getOncontextmenu",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCONTEXTMENU = WebKitNative.downcall("wkj_dom_DOMWindow_setOncontextmenu",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDBLCLICK = WebKitNative.downcall("wkj_dom_DOMWindow_getOndblclick",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDBLCLICK = WebKitNative.downcall("wkj_dom_DOMWindow_setOndblclick",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAG = WebKitNative.downcall("wkj_dom_DOMWindow_getOndrag",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAG = WebKitNative.downcall("wkj_dom_DOMWindow_setOndrag",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGEND = WebKitNative.downcall("wkj_dom_DOMWindow_getOndragend",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGEND = WebKitNative.downcall("wkj_dom_DOMWindow_setOndragend",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGENTER = WebKitNative.downcall("wkj_dom_DOMWindow_getOndragenter",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGENTER = WebKitNative.downcall("wkj_dom_DOMWindow_setOndragenter",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGLEAVE = WebKitNative.downcall("wkj_dom_DOMWindow_getOndragleave",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGLEAVE = WebKitNative.downcall("wkj_dom_DOMWindow_setOndragleave",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGOVER = WebKitNative.downcall("wkj_dom_DOMWindow_getOndragover",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGOVER = WebKitNative.downcall("wkj_dom_DOMWindow_setOndragover",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGSTART = WebKitNative.downcall("wkj_dom_DOMWindow_getOndragstart",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGSTART = WebKitNative.downcall("wkj_dom_DOMWindow_setOndragstart",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDROP = WebKitNative.downcall("wkj_dom_DOMWindow_getOndrop",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDROP = WebKitNative.downcall("wkj_dom_DOMWindow_setOndrop",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDURATIONCHANGE = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOndurationchange", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDURATIONCHANGE = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOndurationchange", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONEMPTIED = WebKitNative.downcall("wkj_dom_DOMWindow_getOnemptied",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONEMPTIED = WebKitNative.downcall("wkj_dom_DOMWindow_setOnemptied",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONENDED = WebKitNative.downcall("wkj_dom_DOMWindow_getOnended",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONENDED = WebKitNative.downcall("wkj_dom_DOMWindow_setOnended",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONERROR = WebKitNative.downcall("wkj_dom_DOMWindow_getOnerror",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONERROR = WebKitNative.downcall("wkj_dom_DOMWindow_setOnerror",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONFOCUS = WebKitNative.downcall("wkj_dom_DOMWindow_getOnfocus",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONFOCUS = WebKitNative.downcall("wkj_dom_DOMWindow_setOnfocus",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONINPUT = WebKitNative.downcall("wkj_dom_DOMWindow_getOninput",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONINPUT = WebKitNative.downcall("wkj_dom_DOMWindow_setOninput",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONINVALID = WebKitNative.downcall("wkj_dom_DOMWindow_getOninvalid",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONINVALID = WebKitNative.downcall("wkj_dom_DOMWindow_setOninvalid",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONKEYDOWN = WebKitNative.downcall("wkj_dom_DOMWindow_getOnkeydown",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONKEYDOWN = WebKitNative.downcall("wkj_dom_DOMWindow_setOnkeydown",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONKEYPRESS = WebKitNative.downcall("wkj_dom_DOMWindow_getOnkeypress",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONKEYPRESS = WebKitNative.downcall("wkj_dom_DOMWindow_setOnkeypress",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONKEYUP = WebKitNative.downcall("wkj_dom_DOMWindow_getOnkeyup",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONKEYUP = WebKitNative.downcall("wkj_dom_DOMWindow_setOnkeyup",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOAD = WebKitNative.downcall("wkj_dom_DOMWindow_getOnload",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOAD = WebKitNative.downcall("wkj_dom_DOMWindow_setOnload",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOADEDDATA = WebKitNative.downcall("wkj_dom_DOMWindow_getOnloadeddata",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOADEDDATA = WebKitNative.downcall("wkj_dom_DOMWindow_setOnloadeddata",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOADEDMETADATA = WebKitNative.downcall(
            "wkj_dom_DOMWindow_getOnloadedmetadata", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOADEDMETADATA = WebKitNative.downcall(
            "wkj_dom_DOMWindow_setOnloadedmetadata", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOADSTART = WebKitNative.downcall("wkj_dom_DOMWindow_getOnloadstart",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOADSTART = WebKitNative.downcall("wkj_dom_DOMWindow_setOnloadstart",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEDOWN = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmousedown",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEDOWN = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmousedown",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEENTER = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmouseenter",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEENTER = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmouseenter",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSELEAVE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmouseleave",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSELEAVE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmouseleave",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEMOVE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmousemove",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEMOVE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmousemove",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEOUT = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmouseout",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEOUT = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmouseout",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEOVER = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmouseover",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEOVER = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmouseover",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEUP = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmouseup",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEUP = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmouseup",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEWHEEL = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmousewheel",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEWHEEL = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmousewheel",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPAUSE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnpause",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPAUSE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnpause",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPLAY = WebKitNative.downcall("wkj_dom_DOMWindow_getOnplay",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPLAY = WebKitNative.downcall("wkj_dom_DOMWindow_setOnplay",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPLAYING = WebKitNative.downcall("wkj_dom_DOMWindow_getOnplaying",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPLAYING = WebKitNative.downcall("wkj_dom_DOMWindow_setOnplaying",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPROGRESS = WebKitNative.downcall("wkj_dom_DOMWindow_getOnprogress",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPROGRESS = WebKitNative.downcall("wkj_dom_DOMWindow_setOnprogress",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONRATECHANGE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnratechange",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONRATECHANGE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnratechange",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONRESET = WebKitNative.downcall("wkj_dom_DOMWindow_getOnreset",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONRESET = WebKitNative.downcall("wkj_dom_DOMWindow_setOnreset",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONRESIZE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnresize",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONRESIZE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnresize",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSCROLL = WebKitNative.downcall("wkj_dom_DOMWindow_getOnscroll",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSCROLL = WebKitNative.downcall("wkj_dom_DOMWindow_setOnscroll",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSEEKED = WebKitNative.downcall("wkj_dom_DOMWindow_getOnseeked",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSEEKED = WebKitNative.downcall("wkj_dom_DOMWindow_setOnseeked",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSEEKING = WebKitNative.downcall("wkj_dom_DOMWindow_getOnseeking",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSEEKING = WebKitNative.downcall("wkj_dom_DOMWindow_setOnseeking",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSELECT = WebKitNative.downcall("wkj_dom_DOMWindow_getOnselect",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSELECT = WebKitNative.downcall("wkj_dom_DOMWindow_setOnselect",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSTALLED = WebKitNative.downcall("wkj_dom_DOMWindow_getOnstalled",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSTALLED = WebKitNative.downcall("wkj_dom_DOMWindow_setOnstalled",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSUBMIT = WebKitNative.downcall("wkj_dom_DOMWindow_getOnsubmit",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSUBMIT = WebKitNative.downcall("wkj_dom_DOMWindow_setOnsubmit",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSUSPEND = WebKitNative.downcall("wkj_dom_DOMWindow_getOnsuspend",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSUSPEND = WebKitNative.downcall("wkj_dom_DOMWindow_setOnsuspend",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONTIMEUPDATE = WebKitNative.downcall("wkj_dom_DOMWindow_getOntimeupdate",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONTIMEUPDATE = WebKitNative.downcall("wkj_dom_DOMWindow_setOntimeupdate",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONVOLUMECHANGE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnvolumechange",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONVOLUMECHANGE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnvolumechange",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWAITING = WebKitNative.downcall("wkj_dom_DOMWindow_getOnwaiting",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWAITING = WebKitNative.downcall("wkj_dom_DOMWindow_setOnwaiting",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWHEEL = WebKitNative.downcall("wkj_dom_DOMWindow_getOnwheel",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWHEEL = WebKitNative.downcall("wkj_dom_DOMWindow_setOnwheel",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONBEFOREUNLOAD = WebKitNative.downcall("wkj_dom_DOMWindow_getOnbeforeunload",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBEFOREUNLOAD = WebKitNative.downcall("wkj_dom_DOMWindow_setOnbeforeunload",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONHASHCHANGE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnhashchange",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONHASHCHANGE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnhashchange",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMESSAGE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnmessage",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMESSAGE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnmessage",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONOFFLINE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnoffline",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONOFFLINE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnoffline",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONONLINE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnonline",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONONLINE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnonline",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPAGEHIDE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnpagehide",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPAGEHIDE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnpagehide",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPAGESHOW = WebKitNative.downcall("wkj_dom_DOMWindow_getOnpageshow",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPAGESHOW = WebKitNative.downcall("wkj_dom_DOMWindow_setOnpageshow",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPOPSTATE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnpopstate",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPOPSTATE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnpopstate",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSTORAGE = WebKitNative.downcall("wkj_dom_DOMWindow_getOnstorage",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSTORAGE = WebKitNative.downcall("wkj_dom_DOMWindow_setOnstorage",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONUNLOAD = WebKitNative.downcall("wkj_dom_DOMWindow_getOnunload",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONUNLOAD = WebKitNative.downcall("wkj_dom_DOMWindow_setOnunload",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_SELECTION = WebKitNative.downcall("wkj_dom_DOMWindow_getSelection",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle FOCUS = WebKitNative.downcall("wkj_dom_DOMWindow_focus",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle BLUR = WebKitNative.downcall("wkj_dom_DOMWindow_blur",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle CLOSE = WebKitNative.downcall("wkj_dom_DOMWindow_close",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle PRINT = WebKitNative.downcall("wkj_dom_DOMWindow_print",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle STOP = WebKitNative.downcall("wkj_dom_DOMWindow_stop",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle ALERT = WebKitNative.downcall("wkj_dom_DOMWindow_alert",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle CONFIRM = WebKitNative.downcall("wkj_dom_DOMWindow_confirm",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle PROMPT = WebKitNative.downcall("wkj_dom_DOMWindow_prompt",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT,
                    ADDRESS));
    private static final MethodHandle FIND = WebKitNative.downcall("wkj_dom_DOMWindow_find",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT,
                    JAVA_INT, JAVA_INT));
    private static final MethodHandle SCROLL_BY = WebKitNative.downcall("wkj_dom_DOMWindow_scrollBy",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT));
    private static final MethodHandle SCROLL_TO = WebKitNative.downcall("wkj_dom_DOMWindow_scrollTo",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT));
    private static final MethodHandle SCROLL = WebKitNative.downcall("wkj_dom_DOMWindow_scroll",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT));
    private static final MethodHandle MOVE_BY = WebKitNative.downcall("wkj_dom_DOMWindow_moveBy",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_FLOAT, JAVA_FLOAT));
    private static final MethodHandle MOVE_TO = WebKitNative.downcall("wkj_dom_DOMWindow_moveTo",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_FLOAT, JAVA_FLOAT));
    private static final MethodHandle RESIZE_BY = WebKitNative.downcall("wkj_dom_DOMWindow_resizeBy",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_FLOAT, JAVA_FLOAT));
    private static final MethodHandle RESIZE_TO = WebKitNative.downcall("wkj_dom_DOMWindow_resizeTo",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_FLOAT, JAVA_FLOAT));
    private static final MethodHandle GET_COMPUTED_STYLE = WebKitNative.downcall("wkj_dom_DOMWindow_getComputedStyle",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle CAPTURE_EVENTS = WebKitNative.downcall("wkj_dom_DOMWindow_captureEvents",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle RELEASE_EVENTS = WebKitNative.downcall("wkj_dom_DOMWindow_releaseEvents",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle ADD_EVENT_LISTENER = WebKitNative.downcall("wkj_dom_DOMWindow_addEventListener",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_LONG, JAVA_INT));
    private static final MethodHandle REMOVE_EVENT_LISTENER = WebKitNative.downcall(
            "wkj_dom_DOMWindow_removeEventListener",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_LONG, JAVA_INT));
    private static final MethodHandle DISPATCH_EVENT = WebKitNative.downcall("wkj_dom_DOMWindow_dispatchEvent",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG));
    private static final MethodHandle ATOB = WebKitNative.downcall("wkj_dom_DOMWindow_atob",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle BTOA = WebKitNative.downcall("wkj_dom_DOMWindow_btoa",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle CLEAR_TIMEOUT = WebKitNative.downcall("wkj_dom_DOMWindow_clearTimeout",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle CLEAR_INTERVAL = WebKitNative.downcall("wkj_dom_DOMWindow_clearInterval",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));

    private DOMWindowNative() {
    }

    static void dispose(long peer) {
        try {
            DISPOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getFrameElement(long peer) {
        try {
            return (long) GET_FRAME_ELEMENT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getOffscreenBuffering(long peer) {
        try {
            return (int) GET_OFFSCREEN_BUFFERING.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getOuterHeight(long peer) {
        try {
            return (int) GET_OUTER_HEIGHT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getOuterWidth(long peer) {
        try {
            return (int) GET_OUTER_WIDTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getInnerHeight(long peer) {
        try {
            return (int) GET_INNER_HEIGHT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getInnerWidth(long peer) {
        try {
            return (int) GET_INNER_WIDTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScreenX(long peer) {
        try {
            return (int) GET_SCREEN_X.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScreenY(long peer) {
        try {
            return (int) GET_SCREEN_Y.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScreenLeft(long peer) {
        try {
            return (int) GET_SCREEN_LEFT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScreenTop(long peer) {
        try {
            return (int) GET_SCREEN_TOP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScrollX(long peer) {
        try {
            return (int) GET_SCROLL_X.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScrollY(long peer) {
        try {
            return (int) GET_SCROLL_Y.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getPageXOffset(long peer) {
        try {
            return (int) GET_PAGE_X_OFFSET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getPageYOffset(long peer) {
        try {
            return (int) GET_PAGE_Y_OFFSET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getClosed(long peer) {
        try {
            return (int) GET_CLOSED.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getLength(long peer) {
        try {
            return (int) GET_LENGTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getName(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_NAME.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_NAME.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setName(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_NAME.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getStatus(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_STATUS.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_STATUS.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setStatus(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_STATUS.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getDefaultStatus(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_DEFAULT_STATUS.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY,
                        resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_DEFAULT_STATUS.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setDefaultStatus(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_DEFAULT_STATUS.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static long getSelf(long peer) {
        try {
            return (long) GET_SELF.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getWindow(long peer) {
        try {
            return (long) GET_WINDOW.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getFrames(long peer) {
        try {
            return (long) GET_FRAMES.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOpener(long peer) {
        try {
            return (long) GET_OPENER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getParent(long peer) {
        try {
            return (long) GET_PARENT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getTop(long peer) {
        try {
            return (long) GET_TOP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getDocumentEx(long peer) {
        try {
            return (long) GET_DOCUMENT_EX.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getDevicePixelRatio(long peer) {
        try {
            return (double) GET_DEVICE_PIXEL_RATIO.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnanimationend(long peer) {
        try {
            return (long) GET_ONANIMATIONEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnanimationend(long peer, long value) {
        try {
            SET_ONANIMATIONEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnanimationiteration(long peer) {
        try {
            return (long) GET_ONANIMATIONITERATION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnanimationiteration(long peer, long value) {
        try {
            SET_ONANIMATIONITERATION.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnanimationstart(long peer) {
        try {
            return (long) GET_ONANIMATIONSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnanimationstart(long peer, long value) {
        try {
            SET_ONANIMATIONSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOntransitionend(long peer) {
        try {
            return (long) GET_ONTRANSITIONEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOntransitionend(long peer, long value) {
        try {
            SET_ONTRANSITIONEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwebkitanimationend(long peer) {
        try {
            return (long) GET_ONWEBKITANIMATIONEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwebkitanimationend(long peer, long value) {
        try {
            SET_ONWEBKITANIMATIONEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwebkitanimationiteration(long peer) {
        try {
            return (long) GET_ONWEBKITANIMATIONITERATION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwebkitanimationiteration(long peer, long value) {
        try {
            SET_ONWEBKITANIMATIONITERATION.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwebkitanimationstart(long peer) {
        try {
            return (long) GET_ONWEBKITANIMATIONSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwebkitanimationstart(long peer, long value) {
        try {
            SET_ONWEBKITANIMATIONSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwebkittransitionend(long peer) {
        try {
            return (long) GET_ONWEBKITTRANSITIONEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwebkittransitionend(long peer, long value) {
        try {
            SET_ONWEBKITTRANSITIONEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnabort(long peer) {
        try {
            return (long) GET_ONABORT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnabort(long peer, long value) {
        try {
            SET_ONABORT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnblur(long peer) {
        try {
            return (long) GET_ONBLUR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnblur(long peer, long value) {
        try {
            SET_ONBLUR.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOncanplay(long peer) {
        try {
            return (long) GET_ONCANPLAY.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOncanplay(long peer, long value) {
        try {
            SET_ONCANPLAY.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOncanplaythrough(long peer) {
        try {
            return (long) GET_ONCANPLAYTHROUGH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOncanplaythrough(long peer, long value) {
        try {
            SET_ONCANPLAYTHROUGH.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnchange(long peer) {
        try {
            return (long) GET_ONCHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnchange(long peer, long value) {
        try {
            SET_ONCHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnclick(long peer) {
        try {
            return (long) GET_ONCLICK.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnclick(long peer, long value) {
        try {
            SET_ONCLICK.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOncontextmenu(long peer) {
        try {
            return (long) GET_ONCONTEXTMENU.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOncontextmenu(long peer, long value) {
        try {
            SET_ONCONTEXTMENU.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndblclick(long peer) {
        try {
            return (long) GET_ONDBLCLICK.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndblclick(long peer, long value) {
        try {
            SET_ONDBLCLICK.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndrag(long peer) {
        try {
            return (long) GET_ONDRAG.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndrag(long peer, long value) {
        try {
            SET_ONDRAG.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragend(long peer) {
        try {
            return (long) GET_ONDRAGEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragend(long peer, long value) {
        try {
            SET_ONDRAGEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragenter(long peer) {
        try {
            return (long) GET_ONDRAGENTER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragenter(long peer, long value) {
        try {
            SET_ONDRAGENTER.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragleave(long peer) {
        try {
            return (long) GET_ONDRAGLEAVE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragleave(long peer, long value) {
        try {
            SET_ONDRAGLEAVE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragover(long peer) {
        try {
            return (long) GET_ONDRAGOVER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragover(long peer, long value) {
        try {
            SET_ONDRAGOVER.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragstart(long peer) {
        try {
            return (long) GET_ONDRAGSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragstart(long peer, long value) {
        try {
            SET_ONDRAGSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndrop(long peer) {
        try {
            return (long) GET_ONDROP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndrop(long peer, long value) {
        try {
            SET_ONDROP.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndurationchange(long peer) {
        try {
            return (long) GET_ONDURATIONCHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndurationchange(long peer, long value) {
        try {
            SET_ONDURATIONCHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnemptied(long peer) {
        try {
            return (long) GET_ONEMPTIED.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnemptied(long peer, long value) {
        try {
            SET_ONEMPTIED.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnended(long peer) {
        try {
            return (long) GET_ONENDED.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnended(long peer, long value) {
        try {
            SET_ONENDED.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnerror(long peer) {
        try {
            return (long) GET_ONERROR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnerror(long peer, long value) {
        try {
            SET_ONERROR.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnfocus(long peer) {
        try {
            return (long) GET_ONFOCUS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnfocus(long peer, long value) {
        try {
            SET_ONFOCUS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOninput(long peer) {
        try {
            return (long) GET_ONINPUT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOninput(long peer, long value) {
        try {
            SET_ONINPUT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOninvalid(long peer) {
        try {
            return (long) GET_ONINVALID.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOninvalid(long peer, long value) {
        try {
            SET_ONINVALID.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnkeydown(long peer) {
        try {
            return (long) GET_ONKEYDOWN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnkeydown(long peer, long value) {
        try {
            SET_ONKEYDOWN.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnkeypress(long peer) {
        try {
            return (long) GET_ONKEYPRESS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnkeypress(long peer, long value) {
        try {
            SET_ONKEYPRESS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnkeyup(long peer) {
        try {
            return (long) GET_ONKEYUP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnkeyup(long peer, long value) {
        try {
            SET_ONKEYUP.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnload(long peer) {
        try {
            return (long) GET_ONLOAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnload(long peer, long value) {
        try {
            SET_ONLOAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnloadeddata(long peer) {
        try {
            return (long) GET_ONLOADEDDATA.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnloadeddata(long peer, long value) {
        try {
            SET_ONLOADEDDATA.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnloadedmetadata(long peer) {
        try {
            return (long) GET_ONLOADEDMETADATA.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnloadedmetadata(long peer, long value) {
        try {
            SET_ONLOADEDMETADATA.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnloadstart(long peer) {
        try {
            return (long) GET_ONLOADSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnloadstart(long peer, long value) {
        try {
            SET_ONLOADSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmousedown(long peer) {
        try {
            return (long) GET_ONMOUSEDOWN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmousedown(long peer, long value) {
        try {
            SET_ONMOUSEDOWN.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseenter(long peer) {
        try {
            return (long) GET_ONMOUSEENTER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseenter(long peer, long value) {
        try {
            SET_ONMOUSEENTER.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseleave(long peer) {
        try {
            return (long) GET_ONMOUSELEAVE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseleave(long peer, long value) {
        try {
            SET_ONMOUSELEAVE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmousemove(long peer) {
        try {
            return (long) GET_ONMOUSEMOVE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmousemove(long peer, long value) {
        try {
            SET_ONMOUSEMOVE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseout(long peer) {
        try {
            return (long) GET_ONMOUSEOUT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseout(long peer, long value) {
        try {
            SET_ONMOUSEOUT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseover(long peer) {
        try {
            return (long) GET_ONMOUSEOVER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseover(long peer, long value) {
        try {
            SET_ONMOUSEOVER.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseup(long peer) {
        try {
            return (long) GET_ONMOUSEUP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseup(long peer, long value) {
        try {
            SET_ONMOUSEUP.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmousewheel(long peer) {
        try {
            return (long) GET_ONMOUSEWHEEL.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmousewheel(long peer, long value) {
        try {
            SET_ONMOUSEWHEEL.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpause(long peer) {
        try {
            return (long) GET_ONPAUSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpause(long peer, long value) {
        try {
            SET_ONPAUSE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnplay(long peer) {
        try {
            return (long) GET_ONPLAY.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnplay(long peer, long value) {
        try {
            SET_ONPLAY.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnplaying(long peer) {
        try {
            return (long) GET_ONPLAYING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnplaying(long peer, long value) {
        try {
            SET_ONPLAYING.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnprogress(long peer) {
        try {
            return (long) GET_ONPROGRESS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnprogress(long peer, long value) {
        try {
            SET_ONPROGRESS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnratechange(long peer) {
        try {
            return (long) GET_ONRATECHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnratechange(long peer, long value) {
        try {
            SET_ONRATECHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnreset(long peer) {
        try {
            return (long) GET_ONRESET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnreset(long peer, long value) {
        try {
            SET_ONRESET.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnresize(long peer) {
        try {
            return (long) GET_ONRESIZE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnresize(long peer, long value) {
        try {
            SET_ONRESIZE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnscroll(long peer) {
        try {
            return (long) GET_ONSCROLL.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnscroll(long peer, long value) {
        try {
            SET_ONSCROLL.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnseeked(long peer) {
        try {
            return (long) GET_ONSEEKED.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnseeked(long peer, long value) {
        try {
            SET_ONSEEKED.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnseeking(long peer) {
        try {
            return (long) GET_ONSEEKING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnseeking(long peer, long value) {
        try {
            SET_ONSEEKING.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnselect(long peer) {
        try {
            return (long) GET_ONSELECT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnselect(long peer, long value) {
        try {
            SET_ONSELECT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnstalled(long peer) {
        try {
            return (long) GET_ONSTALLED.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnstalled(long peer, long value) {
        try {
            SET_ONSTALLED.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnsubmit(long peer) {
        try {
            return (long) GET_ONSUBMIT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnsubmit(long peer, long value) {
        try {
            SET_ONSUBMIT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnsuspend(long peer) {
        try {
            return (long) GET_ONSUSPEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnsuspend(long peer, long value) {
        try {
            SET_ONSUSPEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOntimeupdate(long peer) {
        try {
            return (long) GET_ONTIMEUPDATE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOntimeupdate(long peer, long value) {
        try {
            SET_ONTIMEUPDATE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnvolumechange(long peer) {
        try {
            return (long) GET_ONVOLUMECHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnvolumechange(long peer, long value) {
        try {
            SET_ONVOLUMECHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwaiting(long peer) {
        try {
            return (long) GET_ONWAITING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwaiting(long peer, long value) {
        try {
            SET_ONWAITING.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwheel(long peer) {
        try {
            return (long) GET_ONWHEEL.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwheel(long peer, long value) {
        try {
            SET_ONWHEEL.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnbeforeunload(long peer) {
        try {
            return (long) GET_ONBEFOREUNLOAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnbeforeunload(long peer, long value) {
        try {
            SET_ONBEFOREUNLOAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnhashchange(long peer) {
        try {
            return (long) GET_ONHASHCHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnhashchange(long peer, long value) {
        try {
            SET_ONHASHCHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmessage(long peer) {
        try {
            return (long) GET_ONMESSAGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmessage(long peer, long value) {
        try {
            SET_ONMESSAGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnoffline(long peer) {
        try {
            return (long) GET_ONOFFLINE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnoffline(long peer, long value) {
        try {
            SET_ONOFFLINE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnonline(long peer) {
        try {
            return (long) GET_ONONLINE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnonline(long peer, long value) {
        try {
            SET_ONONLINE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpagehide(long peer) {
        try {
            return (long) GET_ONPAGEHIDE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpagehide(long peer, long value) {
        try {
            SET_ONPAGEHIDE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpageshow(long peer) {
        try {
            return (long) GET_ONPAGESHOW.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpageshow(long peer, long value) {
        try {
            SET_ONPAGESHOW.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpopstate(long peer) {
        try {
            return (long) GET_ONPOPSTATE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpopstate(long peer, long value) {
        try {
            SET_ONPOPSTATE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnstorage(long peer) {
        try {
            return (long) GET_ONSTORAGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnstorage(long peer, long value) {
        try {
            SET_ONSTORAGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnunload(long peer) {
        try {
            return (long) GET_ONUNLOAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnunload(long peer, long value) {
        try {
            SET_ONUNLOAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getSelection(long peer) {
        try {
            return (long) GET_SELECTION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void focus(long peer) {
        try {
            FOCUS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void blur(long peer) {
        try {
            BLUR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void close(long peer) {
        try {
            CLOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void print(long peer) {
        try {
            PRINT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void stop(long peer) {
        try {
            STOP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void alert(long peer, String message) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment messageSegment = WebKitNative.allocString(arena, message);
            try {
                ALERT.invokeExact(peer, messageSegment, WebKitNative.stringLength(message));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static boolean confirm(long peer, String message) {
        int result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment messageSegment = WebKitNative.allocString(arena, message);
            try {
                result = (int) CONFIRM.invokeExact(peer, messageSegment, WebKitNative.stringLength(message));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result != 0;
    }

    static String prompt(long peer, String message, String defaultValue) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment messageSegment = WebKitNative.allocString(arena, message);
            MemorySegment defaultValueSegment = WebKitNative.allocString(arena, defaultValue);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) PROMPT.invokeExact(peer, messageSegment, WebKitNative.stringLength(message),
                        defaultValueSegment, WebKitNative.stringLength(defaultValue), resultBuffer,
                        DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) PROMPT.invokeExact(peer, messageSegment, WebKitNative.stringLength(message),
                            defaultValueSegment, WebKitNative.stringLength(defaultValue), resultBuffer, required,
                            resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static boolean find(long peer, String string, boolean caseSensitive, boolean backwards, boolean wrap,
            boolean wholeWord, boolean searchInFrames, boolean showDialog) {
        int result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment stringSegment = WebKitNative.allocString(arena, string);
            try {
                result = (int) FIND.invokeExact(peer, stringSegment, WebKitNative.stringLength(string),
                        caseSensitive ? 1 : 0, backwards ? 1 : 0, wrap ? 1 : 0, wholeWord ? 1 : 0,
                        searchInFrames ? 1 : 0, showDialog ? 1 : 0);
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result != 0;
    }

    static void scrollBy(long peer, int x, int y) {
        try {
            SCROLL_BY.invokeExact(peer, x, y);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void scrollTo(long peer, int x, int y) {
        try {
            SCROLL_TO.invokeExact(peer, x, y);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void scroll(long peer, int x, int y) {
        try {
            SCROLL.invokeExact(peer, x, y);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void moveBy(long peer, float x, float y) {
        try {
            MOVE_BY.invokeExact(peer, x, y);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void moveTo(long peer, float x, float y) {
        try {
            MOVE_TO.invokeExact(peer, x, y);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void resizeBy(long peer, float x, float y) {
        try {
            RESIZE_BY.invokeExact(peer, x, y);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void resizeTo(long peer, float width, float height) {
        try {
            RESIZE_TO.invokeExact(peer, width, height);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getComputedStyle(long peer, long element, String pseudoElement) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment pseudoElementSegment = WebKitNative.allocString(arena, pseudoElement);
            try {
                result = (long) GET_COMPUTED_STYLE.invokeExact(peer, element, pseudoElementSegment,
                        WebKitNative.stringLength(pseudoElement));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result;
    }

    static void captureEvents(long peer) {
        try {
            CAPTURE_EVENTS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void releaseEvents(long peer) {
        try {
            RELEASE_EVENTS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void addEventListener(long peer, String type, long listener, boolean useCapture) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment typeSegment = WebKitNative.allocString(arena, type);
            try {
                ADD_EVENT_LISTENER.invokeExact(peer, typeSegment, WebKitNative.stringLength(type), listener,
                        useCapture ? 1 : 0);
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void removeEventListener(long peer, String type, long listener, boolean useCapture) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment typeSegment = WebKitNative.allocString(arena, type);
            try {
                REMOVE_EVENT_LISTENER.invokeExact(peer, typeSegment, WebKitNative.stringLength(type), listener,
                        useCapture ? 1 : 0);
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static boolean dispatchEvent(long peer, long event) {
        int result;
        try {
            result = (int) DISPATCH_EVENT.invokeExact(peer, event);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result != 0;
    }

    static String atob(long peer, String string) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment stringSegment = WebKitNative.allocString(arena, string);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) ATOB.invokeExact(peer, stringSegment, WebKitNative.stringLength(string), resultBuffer,
                        DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) ATOB.invokeExact(peer, stringSegment, WebKitNative.stringLength(string),
                            resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            WebKitNative.checkException();
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static String btoa(long peer, String string) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment stringSegment = WebKitNative.allocString(arena, string);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) BTOA.invokeExact(peer, stringSegment, WebKitNative.stringLength(string), resultBuffer,
                        DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) BTOA.invokeExact(peer, stringSegment, WebKitNative.stringLength(string),
                            resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            WebKitNative.checkException();
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void clearTimeout(long peer, int handle) {
        try {
            CLEAR_TIMEOUT.invokeExact(peer, handle);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void clearInterval(long peer, int handle) {
        try {
            CLEAR_INTERVAL.invokeExact(peer, handle);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }
}
