/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_DOUBLE;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * FFM facade for the {@code wkj_dom_Element_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link ElementImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class ElementNative {

    private static final MethodHandle IS_HTML_ELEMENT = WebKitNative.downcall("wkj_dom_Element_isHTMLElement",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_TAG_NAME = WebKitNative.downcall("wkj_dom_Element_getTagName",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_ATTRIBUTES = WebKitNative.downcall("wkj_dom_Element_getAttributes",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_STYLE = WebKitNative.downcall("wkj_dom_Element_getStyle",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ID = WebKitNative.downcall("wkj_dom_Element_getId",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ID = WebKitNative.downcall("wkj_dom_Element_setId",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_OFFSET_LEFT = WebKitNative.downcall("wkj_dom_Element_getOffsetLeft",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_OFFSET_TOP = WebKitNative.downcall("wkj_dom_Element_getOffsetTop",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_OFFSET_WIDTH = WebKitNative.downcall("wkj_dom_Element_getOffsetWidth",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_OFFSET_HEIGHT = WebKitNative.downcall("wkj_dom_Element_getOffsetHeight",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_CLIENT_LEFT = WebKitNative.downcall("wkj_dom_Element_getClientLeft",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_CLIENT_TOP = WebKitNative.downcall("wkj_dom_Element_getClientTop",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_CLIENT_WIDTH = WebKitNative.downcall("wkj_dom_Element_getClientWidth",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_CLIENT_HEIGHT = WebKitNative.downcall("wkj_dom_Element_getClientHeight",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_SCROLL_LEFT = WebKitNative.downcall("wkj_dom_Element_getScrollLeft",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_SCROLL_LEFT = WebKitNative.downcall("wkj_dom_Element_setScrollLeft",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_SCROLL_TOP = WebKitNative.downcall("wkj_dom_Element_getScrollTop",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_SCROLL_TOP = WebKitNative.downcall("wkj_dom_Element_setScrollTop",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_SCROLL_WIDTH = WebKitNative.downcall("wkj_dom_Element_getScrollWidth",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SCROLL_HEIGHT = WebKitNative.downcall("wkj_dom_Element_getScrollHeight",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_OFFSET_PARENT = WebKitNative.downcall("wkj_dom_Element_getOffsetParent",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_INNER_HTML = WebKitNative.downcall("wkj_dom_Element_getInnerHTML",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_INNER_HTML = WebKitNative.downcall("wkj_dom_Element_setInnerHTML",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_OUTER_HTML = WebKitNative.downcall("wkj_dom_Element_getOuterHTML",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_OUTER_HTML = WebKitNative.downcall("wkj_dom_Element_setOuterHTML",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_CLASS_NAME = WebKitNative.downcall("wkj_dom_Element_getClassName",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_CLASS_NAME = WebKitNative.downcall("wkj_dom_Element_setClassName",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ONBEFORECOPY = WebKitNative.downcall("wkj_dom_Element_getOnbeforecopy",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBEFORECOPY = WebKitNative.downcall("wkj_dom_Element_setOnbeforecopy",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONBEFORECUT = WebKitNative.downcall("wkj_dom_Element_getOnbeforecut",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBEFORECUT = WebKitNative.downcall("wkj_dom_Element_setOnbeforecut",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONBEFOREPASTE = WebKitNative.downcall("wkj_dom_Element_getOnbeforepaste",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBEFOREPASTE = WebKitNative.downcall("wkj_dom_Element_setOnbeforepaste",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCOPY = WebKitNative.downcall("wkj_dom_Element_getOncopy",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCOPY = WebKitNative.downcall("wkj_dom_Element_setOncopy",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCUT = WebKitNative.downcall("wkj_dom_Element_getOncut",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCUT = WebKitNative.downcall("wkj_dom_Element_setOncut",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPASTE = WebKitNative.downcall("wkj_dom_Element_getOnpaste",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPASTE = WebKitNative.downcall("wkj_dom_Element_setOnpaste",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSELECTSTART = WebKitNative.downcall("wkj_dom_Element_getOnselectstart",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSELECTSTART = WebKitNative.downcall("wkj_dom_Element_setOnselectstart",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONANIMATIONEND = WebKitNative.downcall("wkj_dom_Element_getOnanimationend",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONANIMATIONEND = WebKitNative.downcall("wkj_dom_Element_setOnanimationend",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONANIMATIONITERATION = WebKitNative.downcall(
            "wkj_dom_Element_getOnanimationiteration", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONANIMATIONITERATION = WebKitNative.downcall(
            "wkj_dom_Element_setOnanimationiteration", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONANIMATIONSTART = WebKitNative.downcall(
            "wkj_dom_Element_getOnanimationstart", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONANIMATIONSTART = WebKitNative.downcall(
            "wkj_dom_Element_setOnanimationstart", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONTRANSITIONEND = WebKitNative.downcall("wkj_dom_Element_getOntransitionend",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONTRANSITIONEND = WebKitNative.downcall("wkj_dom_Element_setOntransitionend",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWEBKITANIMATIONEND = WebKitNative.downcall(
            "wkj_dom_Element_getOnwebkitanimationend", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWEBKITANIMATIONEND = WebKitNative.downcall(
            "wkj_dom_Element_setOnwebkitanimationend", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWEBKITANIMATIONITERATION = WebKitNative.downcall(
            "wkj_dom_Element_getOnwebkitanimationiteration", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWEBKITANIMATIONITERATION = WebKitNative.downcall(
            "wkj_dom_Element_setOnwebkitanimationiteration", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWEBKITANIMATIONSTART = WebKitNative.downcall(
            "wkj_dom_Element_getOnwebkitanimationstart", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWEBKITANIMATIONSTART = WebKitNative.downcall(
            "wkj_dom_Element_setOnwebkitanimationstart", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWEBKITTRANSITIONEND = WebKitNative.downcall(
            "wkj_dom_Element_getOnwebkittransitionend", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWEBKITTRANSITIONEND = WebKitNative.downcall(
            "wkj_dom_Element_setOnwebkittransitionend", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONFOCUSIN = WebKitNative.downcall("wkj_dom_Element_getOnfocusin",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONFOCUSIN = WebKitNative.downcall("wkj_dom_Element_setOnfocusin",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONFOCUSOUT = WebKitNative.downcall("wkj_dom_Element_getOnfocusout",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONFOCUSOUT = WebKitNative.downcall("wkj_dom_Element_setOnfocusout",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONBEFORELOAD = WebKitNative.downcall("wkj_dom_Element_getOnbeforeload",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBEFORELOAD = WebKitNative.downcall("wkj_dom_Element_setOnbeforeload",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONABORT = WebKitNative.downcall("wkj_dom_Element_getOnabort",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONABORT = WebKitNative.downcall("wkj_dom_Element_setOnabort",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONBLUR = WebKitNative.downcall("wkj_dom_Element_getOnblur",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBLUR = WebKitNative.downcall("wkj_dom_Element_setOnblur",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCANPLAY = WebKitNative.downcall("wkj_dom_Element_getOncanplay",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCANPLAY = WebKitNative.downcall("wkj_dom_Element_setOncanplay",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCANPLAYTHROUGH = WebKitNative.downcall(
            "wkj_dom_Element_getOncanplaythrough", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCANPLAYTHROUGH = WebKitNative.downcall(
            "wkj_dom_Element_setOncanplaythrough", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCHANGE = WebKitNative.downcall("wkj_dom_Element_getOnchange",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCHANGE = WebKitNative.downcall("wkj_dom_Element_setOnchange",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCLICK = WebKitNative.downcall("wkj_dom_Element_getOnclick",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCLICK = WebKitNative.downcall("wkj_dom_Element_setOnclick",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONCONTEXTMENU = WebKitNative.downcall("wkj_dom_Element_getOncontextmenu",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONCONTEXTMENU = WebKitNative.downcall("wkj_dom_Element_setOncontextmenu",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDBLCLICK = WebKitNative.downcall("wkj_dom_Element_getOndblclick",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDBLCLICK = WebKitNative.downcall("wkj_dom_Element_setOndblclick",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAG = WebKitNative.downcall("wkj_dom_Element_getOndrag",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAG = WebKitNative.downcall("wkj_dom_Element_setOndrag",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGEND = WebKitNative.downcall("wkj_dom_Element_getOndragend",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGEND = WebKitNative.downcall("wkj_dom_Element_setOndragend",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGENTER = WebKitNative.downcall("wkj_dom_Element_getOndragenter",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGENTER = WebKitNative.downcall("wkj_dom_Element_setOndragenter",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGLEAVE = WebKitNative.downcall("wkj_dom_Element_getOndragleave",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGLEAVE = WebKitNative.downcall("wkj_dom_Element_setOndragleave",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGOVER = WebKitNative.downcall("wkj_dom_Element_getOndragover",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGOVER = WebKitNative.downcall("wkj_dom_Element_setOndragover",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDRAGSTART = WebKitNative.downcall("wkj_dom_Element_getOndragstart",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDRAGSTART = WebKitNative.downcall("wkj_dom_Element_setOndragstart",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDROP = WebKitNative.downcall("wkj_dom_Element_getOndrop",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDROP = WebKitNative.downcall("wkj_dom_Element_setOndrop",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONDURATIONCHANGE = WebKitNative.downcall(
            "wkj_dom_Element_getOndurationchange", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONDURATIONCHANGE = WebKitNative.downcall(
            "wkj_dom_Element_setOndurationchange", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONEMPTIED = WebKitNative.downcall("wkj_dom_Element_getOnemptied",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONEMPTIED = WebKitNative.downcall("wkj_dom_Element_setOnemptied",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONENDED = WebKitNative.downcall("wkj_dom_Element_getOnended",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONENDED = WebKitNative.downcall("wkj_dom_Element_setOnended",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONERROR = WebKitNative.downcall("wkj_dom_Element_getOnerror",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONERROR = WebKitNative.downcall("wkj_dom_Element_setOnerror",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONFOCUS = WebKitNative.downcall("wkj_dom_Element_getOnfocus",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONFOCUS = WebKitNative.downcall("wkj_dom_Element_setOnfocus",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONINPUT = WebKitNative.downcall("wkj_dom_Element_getOninput",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONINPUT = WebKitNative.downcall("wkj_dom_Element_setOninput",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONINVALID = WebKitNative.downcall("wkj_dom_Element_getOninvalid",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONINVALID = WebKitNative.downcall("wkj_dom_Element_setOninvalid",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONKEYDOWN = WebKitNative.downcall("wkj_dom_Element_getOnkeydown",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONKEYDOWN = WebKitNative.downcall("wkj_dom_Element_setOnkeydown",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONKEYPRESS = WebKitNative.downcall("wkj_dom_Element_getOnkeypress",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONKEYPRESS = WebKitNative.downcall("wkj_dom_Element_setOnkeypress",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONKEYUP = WebKitNative.downcall("wkj_dom_Element_getOnkeyup",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONKEYUP = WebKitNative.downcall("wkj_dom_Element_setOnkeyup",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOAD = WebKitNative.downcall("wkj_dom_Element_getOnload",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOAD = WebKitNative.downcall("wkj_dom_Element_setOnload",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOADEDDATA = WebKitNative.downcall("wkj_dom_Element_getOnloadeddata",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOADEDDATA = WebKitNative.downcall("wkj_dom_Element_setOnloadeddata",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOADEDMETADATA = WebKitNative.downcall(
            "wkj_dom_Element_getOnloadedmetadata", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOADEDMETADATA = WebKitNative.downcall(
            "wkj_dom_Element_setOnloadedmetadata", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOADSTART = WebKitNative.downcall("wkj_dom_Element_getOnloadstart",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOADSTART = WebKitNative.downcall("wkj_dom_Element_setOnloadstart",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEDOWN = WebKitNative.downcall("wkj_dom_Element_getOnmousedown",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEDOWN = WebKitNative.downcall("wkj_dom_Element_setOnmousedown",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEENTER = WebKitNative.downcall("wkj_dom_Element_getOnmouseenter",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEENTER = WebKitNative.downcall("wkj_dom_Element_setOnmouseenter",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSELEAVE = WebKitNative.downcall("wkj_dom_Element_getOnmouseleave",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSELEAVE = WebKitNative.downcall("wkj_dom_Element_setOnmouseleave",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEMOVE = WebKitNative.downcall("wkj_dom_Element_getOnmousemove",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEMOVE = WebKitNative.downcall("wkj_dom_Element_setOnmousemove",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEOUT = WebKitNative.downcall("wkj_dom_Element_getOnmouseout",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEOUT = WebKitNative.downcall("wkj_dom_Element_setOnmouseout",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEOVER = WebKitNative.downcall("wkj_dom_Element_getOnmouseover",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEOVER = WebKitNative.downcall("wkj_dom_Element_setOnmouseover",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEUP = WebKitNative.downcall("wkj_dom_Element_getOnmouseup",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEUP = WebKitNative.downcall("wkj_dom_Element_setOnmouseup",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMOUSEWHEEL = WebKitNative.downcall("wkj_dom_Element_getOnmousewheel",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMOUSEWHEEL = WebKitNative.downcall("wkj_dom_Element_setOnmousewheel",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPAUSE = WebKitNative.downcall("wkj_dom_Element_getOnpause",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPAUSE = WebKitNative.downcall("wkj_dom_Element_setOnpause",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPLAY = WebKitNative.downcall("wkj_dom_Element_getOnplay",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPLAY = WebKitNative.downcall("wkj_dom_Element_setOnplay",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPLAYING = WebKitNative.downcall("wkj_dom_Element_getOnplaying",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPLAYING = WebKitNative.downcall("wkj_dom_Element_setOnplaying",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPROGRESS = WebKitNative.downcall("wkj_dom_Element_getOnprogress",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPROGRESS = WebKitNative.downcall("wkj_dom_Element_setOnprogress",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONRATECHANGE = WebKitNative.downcall("wkj_dom_Element_getOnratechange",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONRATECHANGE = WebKitNative.downcall("wkj_dom_Element_setOnratechange",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONRESET = WebKitNative.downcall("wkj_dom_Element_getOnreset",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONRESET = WebKitNative.downcall("wkj_dom_Element_setOnreset",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONRESIZE = WebKitNative.downcall("wkj_dom_Element_getOnresize",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONRESIZE = WebKitNative.downcall("wkj_dom_Element_setOnresize",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSCROLL = WebKitNative.downcall("wkj_dom_Element_getOnscroll",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSCROLL = WebKitNative.downcall("wkj_dom_Element_setOnscroll",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSEEKED = WebKitNative.downcall("wkj_dom_Element_getOnseeked",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSEEKED = WebKitNative.downcall("wkj_dom_Element_setOnseeked",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSEEKING = WebKitNative.downcall("wkj_dom_Element_getOnseeking",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSEEKING = WebKitNative.downcall("wkj_dom_Element_setOnseeking",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSELECT = WebKitNative.downcall("wkj_dom_Element_getOnselect",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSELECT = WebKitNative.downcall("wkj_dom_Element_setOnselect",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSTALLED = WebKitNative.downcall("wkj_dom_Element_getOnstalled",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSTALLED = WebKitNative.downcall("wkj_dom_Element_setOnstalled",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSUBMIT = WebKitNative.downcall("wkj_dom_Element_getOnsubmit",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSUBMIT = WebKitNative.downcall("wkj_dom_Element_setOnsubmit",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSUSPEND = WebKitNative.downcall("wkj_dom_Element_getOnsuspend",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSUSPEND = WebKitNative.downcall("wkj_dom_Element_setOnsuspend",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONTIMEUPDATE = WebKitNative.downcall("wkj_dom_Element_getOntimeupdate",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONTIMEUPDATE = WebKitNative.downcall("wkj_dom_Element_setOntimeupdate",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONVOLUMECHANGE = WebKitNative.downcall("wkj_dom_Element_getOnvolumechange",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONVOLUMECHANGE = WebKitNative.downcall("wkj_dom_Element_setOnvolumechange",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWAITING = WebKitNative.downcall("wkj_dom_Element_getOnwaiting",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWAITING = WebKitNative.downcall("wkj_dom_Element_setOnwaiting",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONWHEEL = WebKitNative.downcall("wkj_dom_Element_getOnwheel",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONWHEEL = WebKitNative.downcall("wkj_dom_Element_setOnwheel",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_PREVIOUS_ELEMENT_SIBLING = WebKitNative.downcall(
            "wkj_dom_Element_getPreviousElementSibling", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_NEXT_ELEMENT_SIBLING = WebKitNative.downcall(
            "wkj_dom_Element_getNextElementSibling", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_CHILDREN = WebKitNative.downcall("wkj_dom_Element_getChildren",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_FIRST_ELEMENT_CHILD = WebKitNative.downcall(
            "wkj_dom_Element_getFirstElementChild", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_LAST_ELEMENT_CHILD = WebKitNative.downcall(
            "wkj_dom_Element_getLastElementChild", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_CHILD_ELEMENT_COUNT = WebKitNative.downcall(
            "wkj_dom_Element_getChildElementCount", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_ATTRIBUTE = WebKitNative.downcall("wkj_dom_Element_getAttribute",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ATTRIBUTE = WebKitNative.downcall("wkj_dom_Element_setAttribute",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle REMOVE_ATTRIBUTE = WebKitNative.downcall("wkj_dom_Element_removeAttribute",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ATTRIBUTE_NODE = WebKitNative.downcall("wkj_dom_Element_getAttributeNode",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle SET_ATTRIBUTE_NODE = WebKitNative.downcall("wkj_dom_Element_setAttributeNode",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG));
    private static final MethodHandle REMOVE_ATTRIBUTE_NODE = WebKitNative.downcall(
            "wkj_dom_Element_removeAttributeNode", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ELEMENTS_BY_TAG_NAME = WebKitNative.downcall(
            "wkj_dom_Element_getElementsByTagName", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle HAS_ATTRIBUTES = WebKitNative.downcall("wkj_dom_Element_hasAttributes",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_ATTRIBUTE_NS = WebKitNative.downcall("wkj_dom_Element_getAttributeNS",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT,
                    ADDRESS));
    private static final MethodHandle SET_ATTRIBUTE_NS = WebKitNative.downcall("wkj_dom_Element_setAttributeNS",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle REMOVE_ATTRIBUTE_NS = WebKitNative.downcall("wkj_dom_Element_removeAttributeNS",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ELEMENTS_BY_TAG_NAME_NS = WebKitNative.downcall(
            "wkj_dom_Element_getElementsByTagNameNS",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ATTRIBUTE_NODE_NS = WebKitNative.downcall(
            "wkj_dom_Element_getAttributeNodeNS",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle SET_ATTRIBUTE_NODE_NS = WebKitNative.downcall(
            "wkj_dom_Element_setAttributeNodeNS", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_LONG));
    private static final MethodHandle HAS_ATTRIBUTE = WebKitNative.downcall("wkj_dom_Element_hasAttribute",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle HAS_ATTRIBUTE_NS = WebKitNative.downcall("wkj_dom_Element_hasAttributeNS",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle FOCUS = WebKitNative.downcall("wkj_dom_Element_focus",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle BLUR = WebKitNative.downcall("wkj_dom_Element_blur",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle SCROLL_INTO_VIEW = WebKitNative.downcall("wkj_dom_Element_scrollIntoView",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle SCROLL_INTO_VIEW_IF_NEEDED = WebKitNative.downcall(
            "wkj_dom_Element_scrollIntoViewIfNeeded", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_ELEMENTS_BY_CLASS_NAME = WebKitNative.downcall(
            "wkj_dom_Element_getElementsByClassName", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle MATCHES = WebKitNative.downcall("wkj_dom_Element_matches",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle CLOSEST = WebKitNative.downcall("wkj_dom_Element_closest",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle WEBKIT_MATCHES_SELECTOR = WebKitNative.downcall(
            "wkj_dom_Element_webkitMatchesSelector", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle WEBKIT_REQUEST_FULL_SCREEN = WebKitNative.downcall(
            "wkj_dom_Element_webkitRequestFullScreen", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_SHORT));
    private static final MethodHandle WEBKIT_REQUEST_FULLSCREEN = WebKitNative.downcall(
            "wkj_dom_Element_webkitRequestFullscreen", FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle REMOVE = WebKitNative.downcall("wkj_dom_Element_remove",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle QUERY_SELECTOR = WebKitNative.downcall("wkj_dom_Element_querySelector",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle QUERY_SELECTOR_ALL = WebKitNative.downcall("wkj_dom_Element_querySelectorAll",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));

    private ElementNative() {
    }

    static boolean isHTMLElement(long peer) {
        try {
            return (int) IS_HTML_ELEMENT.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getTagName(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_TAG_NAME.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_TAG_NAME.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static long getAttributes(long peer) {
        try {
            return (long) GET_ATTRIBUTES.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getStyle(long peer) {
        try {
            return (long) GET_STYLE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getId(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ID.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ID.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setId(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ID.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static double getOffsetLeft(long peer) {
        try {
            return (double) GET_OFFSET_LEFT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getOffsetTop(long peer) {
        try {
            return (double) GET_OFFSET_TOP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getOffsetWidth(long peer) {
        try {
            return (double) GET_OFFSET_WIDTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getOffsetHeight(long peer) {
        try {
            return (double) GET_OFFSET_HEIGHT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getClientLeft(long peer) {
        try {
            return (double) GET_CLIENT_LEFT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getClientTop(long peer) {
        try {
            return (double) GET_CLIENT_TOP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getClientWidth(long peer) {
        try {
            return (double) GET_CLIENT_WIDTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getClientHeight(long peer) {
        try {
            return (double) GET_CLIENT_HEIGHT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScrollLeft(long peer) {
        try {
            return (int) GET_SCROLL_LEFT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setScrollLeft(long peer, int value) {
        try {
            SET_SCROLL_LEFT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScrollTop(long peer) {
        try {
            return (int) GET_SCROLL_TOP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setScrollTop(long peer, int value) {
        try {
            SET_SCROLL_TOP.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScrollWidth(long peer) {
        try {
            return (int) GET_SCROLL_WIDTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScrollHeight(long peer) {
        try {
            return (int) GET_SCROLL_HEIGHT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOffsetParent(long peer) {
        try {
            return (long) GET_OFFSET_PARENT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getInnerHTML(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_INNER_HTML.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_INNER_HTML.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setInnerHTML(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_INNER_HTML.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getOuterHTML(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_OUTER_HTML.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_OUTER_HTML.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setOuterHTML(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_OUTER_HTML.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getClassName(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_CLASS_NAME.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_CLASS_NAME.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setClassName(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_CLASS_NAME.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static long getOnbeforecopy(long peer) {
        try {
            return (long) GET_ONBEFORECOPY.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnbeforecopy(long peer, long value) {
        try {
            SET_ONBEFORECOPY.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnbeforecut(long peer) {
        try {
            return (long) GET_ONBEFORECUT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnbeforecut(long peer, long value) {
        try {
            SET_ONBEFORECUT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnbeforepaste(long peer) {
        try {
            return (long) GET_ONBEFOREPASTE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnbeforepaste(long peer, long value) {
        try {
            SET_ONBEFOREPASTE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOncopy(long peer) {
        try {
            return (long) GET_ONCOPY.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOncopy(long peer, long value) {
        try {
            SET_ONCOPY.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOncut(long peer) {
        try {
            return (long) GET_ONCUT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOncut(long peer, long value) {
        try {
            SET_ONCUT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpaste(long peer) {
        try {
            return (long) GET_ONPASTE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpaste(long peer, long value) {
        try {
            SET_ONPASTE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnselectstart(long peer) {
        try {
            return (long) GET_ONSELECTSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnselectstart(long peer, long value) {
        try {
            SET_ONSELECTSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnanimationend(long peer) {
        try {
            return (long) GET_ONANIMATIONEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnanimationend(long peer, long value) {
        try {
            SET_ONANIMATIONEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnanimationiteration(long peer) {
        try {
            return (long) GET_ONANIMATIONITERATION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnanimationiteration(long peer, long value) {
        try {
            SET_ONANIMATIONITERATION.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnanimationstart(long peer) {
        try {
            return (long) GET_ONANIMATIONSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnanimationstart(long peer, long value) {
        try {
            SET_ONANIMATIONSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOntransitionend(long peer) {
        try {
            return (long) GET_ONTRANSITIONEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOntransitionend(long peer, long value) {
        try {
            SET_ONTRANSITIONEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwebkitanimationend(long peer) {
        try {
            return (long) GET_ONWEBKITANIMATIONEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwebkitanimationend(long peer, long value) {
        try {
            SET_ONWEBKITANIMATIONEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwebkitanimationiteration(long peer) {
        try {
            return (long) GET_ONWEBKITANIMATIONITERATION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwebkitanimationiteration(long peer, long value) {
        try {
            SET_ONWEBKITANIMATIONITERATION.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwebkitanimationstart(long peer) {
        try {
            return (long) GET_ONWEBKITANIMATIONSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwebkitanimationstart(long peer, long value) {
        try {
            SET_ONWEBKITANIMATIONSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwebkittransitionend(long peer) {
        try {
            return (long) GET_ONWEBKITTRANSITIONEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwebkittransitionend(long peer, long value) {
        try {
            SET_ONWEBKITTRANSITIONEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnfocusin(long peer) {
        try {
            return (long) GET_ONFOCUSIN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnfocusin(long peer, long value) {
        try {
            SET_ONFOCUSIN.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnfocusout(long peer) {
        try {
            return (long) GET_ONFOCUSOUT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnfocusout(long peer, long value) {
        try {
            SET_ONFOCUSOUT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnbeforeload(long peer) {
        try {
            return (long) GET_ONBEFORELOAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnbeforeload(long peer, long value) {
        try {
            SET_ONBEFORELOAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnabort(long peer) {
        try {
            return (long) GET_ONABORT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnabort(long peer, long value) {
        try {
            SET_ONABORT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnblur(long peer) {
        try {
            return (long) GET_ONBLUR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnblur(long peer, long value) {
        try {
            SET_ONBLUR.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOncanplay(long peer) {
        try {
            return (long) GET_ONCANPLAY.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOncanplay(long peer, long value) {
        try {
            SET_ONCANPLAY.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOncanplaythrough(long peer) {
        try {
            return (long) GET_ONCANPLAYTHROUGH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOncanplaythrough(long peer, long value) {
        try {
            SET_ONCANPLAYTHROUGH.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnchange(long peer) {
        try {
            return (long) GET_ONCHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnchange(long peer, long value) {
        try {
            SET_ONCHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnclick(long peer) {
        try {
            return (long) GET_ONCLICK.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnclick(long peer, long value) {
        try {
            SET_ONCLICK.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOncontextmenu(long peer) {
        try {
            return (long) GET_ONCONTEXTMENU.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOncontextmenu(long peer, long value) {
        try {
            SET_ONCONTEXTMENU.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndblclick(long peer) {
        try {
            return (long) GET_ONDBLCLICK.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndblclick(long peer, long value) {
        try {
            SET_ONDBLCLICK.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndrag(long peer) {
        try {
            return (long) GET_ONDRAG.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndrag(long peer, long value) {
        try {
            SET_ONDRAG.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragend(long peer) {
        try {
            return (long) GET_ONDRAGEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragend(long peer, long value) {
        try {
            SET_ONDRAGEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragenter(long peer) {
        try {
            return (long) GET_ONDRAGENTER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragenter(long peer, long value) {
        try {
            SET_ONDRAGENTER.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragleave(long peer) {
        try {
            return (long) GET_ONDRAGLEAVE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragleave(long peer, long value) {
        try {
            SET_ONDRAGLEAVE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragover(long peer) {
        try {
            return (long) GET_ONDRAGOVER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragover(long peer, long value) {
        try {
            SET_ONDRAGOVER.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndragstart(long peer) {
        try {
            return (long) GET_ONDRAGSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndragstart(long peer, long value) {
        try {
            SET_ONDRAGSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndrop(long peer) {
        try {
            return (long) GET_ONDROP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndrop(long peer, long value) {
        try {
            SET_ONDROP.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOndurationchange(long peer) {
        try {
            return (long) GET_ONDURATIONCHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOndurationchange(long peer, long value) {
        try {
            SET_ONDURATIONCHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnemptied(long peer) {
        try {
            return (long) GET_ONEMPTIED.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnemptied(long peer, long value) {
        try {
            SET_ONEMPTIED.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnended(long peer) {
        try {
            return (long) GET_ONENDED.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnended(long peer, long value) {
        try {
            SET_ONENDED.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnerror(long peer) {
        try {
            return (long) GET_ONERROR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnerror(long peer, long value) {
        try {
            SET_ONERROR.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnfocus(long peer) {
        try {
            return (long) GET_ONFOCUS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnfocus(long peer, long value) {
        try {
            SET_ONFOCUS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOninput(long peer) {
        try {
            return (long) GET_ONINPUT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOninput(long peer, long value) {
        try {
            SET_ONINPUT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOninvalid(long peer) {
        try {
            return (long) GET_ONINVALID.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOninvalid(long peer, long value) {
        try {
            SET_ONINVALID.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnkeydown(long peer) {
        try {
            return (long) GET_ONKEYDOWN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnkeydown(long peer, long value) {
        try {
            SET_ONKEYDOWN.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnkeypress(long peer) {
        try {
            return (long) GET_ONKEYPRESS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnkeypress(long peer, long value) {
        try {
            SET_ONKEYPRESS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnkeyup(long peer) {
        try {
            return (long) GET_ONKEYUP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnkeyup(long peer, long value) {
        try {
            SET_ONKEYUP.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnload(long peer) {
        try {
            return (long) GET_ONLOAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnload(long peer, long value) {
        try {
            SET_ONLOAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnloadeddata(long peer) {
        try {
            return (long) GET_ONLOADEDDATA.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnloadeddata(long peer, long value) {
        try {
            SET_ONLOADEDDATA.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnloadedmetadata(long peer) {
        try {
            return (long) GET_ONLOADEDMETADATA.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnloadedmetadata(long peer, long value) {
        try {
            SET_ONLOADEDMETADATA.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnloadstart(long peer) {
        try {
            return (long) GET_ONLOADSTART.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnloadstart(long peer, long value) {
        try {
            SET_ONLOADSTART.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmousedown(long peer) {
        try {
            return (long) GET_ONMOUSEDOWN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmousedown(long peer, long value) {
        try {
            SET_ONMOUSEDOWN.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseenter(long peer) {
        try {
            return (long) GET_ONMOUSEENTER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseenter(long peer, long value) {
        try {
            SET_ONMOUSEENTER.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseleave(long peer) {
        try {
            return (long) GET_ONMOUSELEAVE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseleave(long peer, long value) {
        try {
            SET_ONMOUSELEAVE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmousemove(long peer) {
        try {
            return (long) GET_ONMOUSEMOVE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmousemove(long peer, long value) {
        try {
            SET_ONMOUSEMOVE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseout(long peer) {
        try {
            return (long) GET_ONMOUSEOUT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseout(long peer, long value) {
        try {
            SET_ONMOUSEOUT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseover(long peer) {
        try {
            return (long) GET_ONMOUSEOVER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseover(long peer, long value) {
        try {
            SET_ONMOUSEOVER.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmouseup(long peer) {
        try {
            return (long) GET_ONMOUSEUP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmouseup(long peer, long value) {
        try {
            SET_ONMOUSEUP.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmousewheel(long peer) {
        try {
            return (long) GET_ONMOUSEWHEEL.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmousewheel(long peer, long value) {
        try {
            SET_ONMOUSEWHEEL.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpause(long peer) {
        try {
            return (long) GET_ONPAUSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpause(long peer, long value) {
        try {
            SET_ONPAUSE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnplay(long peer) {
        try {
            return (long) GET_ONPLAY.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnplay(long peer, long value) {
        try {
            SET_ONPLAY.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnplaying(long peer) {
        try {
            return (long) GET_ONPLAYING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnplaying(long peer, long value) {
        try {
            SET_ONPLAYING.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnprogress(long peer) {
        try {
            return (long) GET_ONPROGRESS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnprogress(long peer, long value) {
        try {
            SET_ONPROGRESS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnratechange(long peer) {
        try {
            return (long) GET_ONRATECHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnratechange(long peer, long value) {
        try {
            SET_ONRATECHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnreset(long peer) {
        try {
            return (long) GET_ONRESET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnreset(long peer, long value) {
        try {
            SET_ONRESET.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnresize(long peer) {
        try {
            return (long) GET_ONRESIZE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnresize(long peer, long value) {
        try {
            SET_ONRESIZE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnscroll(long peer) {
        try {
            return (long) GET_ONSCROLL.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnscroll(long peer, long value) {
        try {
            SET_ONSCROLL.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnseeked(long peer) {
        try {
            return (long) GET_ONSEEKED.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnseeked(long peer, long value) {
        try {
            SET_ONSEEKED.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnseeking(long peer) {
        try {
            return (long) GET_ONSEEKING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnseeking(long peer, long value) {
        try {
            SET_ONSEEKING.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnselect(long peer) {
        try {
            return (long) GET_ONSELECT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnselect(long peer, long value) {
        try {
            SET_ONSELECT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnstalled(long peer) {
        try {
            return (long) GET_ONSTALLED.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnstalled(long peer, long value) {
        try {
            SET_ONSTALLED.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnsubmit(long peer) {
        try {
            return (long) GET_ONSUBMIT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnsubmit(long peer, long value) {
        try {
            SET_ONSUBMIT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnsuspend(long peer) {
        try {
            return (long) GET_ONSUSPEND.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnsuspend(long peer, long value) {
        try {
            SET_ONSUSPEND.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOntimeupdate(long peer) {
        try {
            return (long) GET_ONTIMEUPDATE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOntimeupdate(long peer, long value) {
        try {
            SET_ONTIMEUPDATE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnvolumechange(long peer) {
        try {
            return (long) GET_ONVOLUMECHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnvolumechange(long peer, long value) {
        try {
            SET_ONVOLUMECHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwaiting(long peer) {
        try {
            return (long) GET_ONWAITING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwaiting(long peer, long value) {
        try {
            SET_ONWAITING.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnwheel(long peer) {
        try {
            return (long) GET_ONWHEEL.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnwheel(long peer, long value) {
        try {
            SET_ONWHEEL.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getPreviousElementSibling(long peer) {
        try {
            return (long) GET_PREVIOUS_ELEMENT_SIBLING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getNextElementSibling(long peer) {
        try {
            return (long) GET_NEXT_ELEMENT_SIBLING.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getChildren(long peer) {
        try {
            return (long) GET_CHILDREN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getFirstElementChild(long peer) {
        try {
            return (long) GET_FIRST_ELEMENT_CHILD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getLastElementChild(long peer) {
        try {
            return (long) GET_LAST_ELEMENT_CHILD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getChildElementCount(long peer) {
        try {
            return (int) GET_CHILD_ELEMENT_COUNT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getAttribute(long peer, String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment nameSegment = WebKitNative.allocString(arena, name);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ATTRIBUTE.invokeExact(peer, nameSegment, WebKitNative.stringLength(name),
                        resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ATTRIBUTE.invokeExact(peer, nameSegment, WebKitNative.stringLength(name),
                            resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAttribute(long peer, String name, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment nameSegment = WebKitNative.allocString(arena, name);
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ATTRIBUTE.invokeExact(peer, nameSegment, WebKitNative.stringLength(name), valueSegment,
                        WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
    }

    static void removeAttribute(long peer, String name) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment nameSegment = WebKitNative.allocString(arena, name);
            try {
                REMOVE_ATTRIBUTE.invokeExact(peer, nameSegment, WebKitNative.stringLength(name));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static long getAttributeNode(long peer, String name) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment nameSegment = WebKitNative.allocString(arena, name);
            try {
                result = (long) GET_ATTRIBUTE_NODE.invokeExact(peer, nameSegment, WebKitNative.stringLength(name));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result;
    }

    static long setAttributeNode(long peer, long newAttr) {
        long result;
        try {
            result = (long) SET_ATTRIBUTE_NODE.invokeExact(peer, newAttr);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static long removeAttributeNode(long peer, long oldAttr) {
        long result;
        try {
            result = (long) REMOVE_ATTRIBUTE_NODE.invokeExact(peer, oldAttr);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static long getElementsByTagName(long peer, String name) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment nameSegment = WebKitNative.allocString(arena, name);
            try {
                result = (long) GET_ELEMENTS_BY_TAG_NAME.invokeExact(peer, nameSegment,
                        WebKitNative.stringLength(name));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result;
    }

    static boolean hasAttributes(long peer) {
        try {
            return (int) HAS_ATTRIBUTES.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getAttributeNS(long peer, String namespaceURI, String localName) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment namespaceURISegment = WebKitNative.allocString(arena, namespaceURI);
            MemorySegment localNameSegment = WebKitNative.allocString(arena, localName);
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ATTRIBUTE_NS.invokeExact(peer, namespaceURISegment,
                        WebKitNative.stringLength(namespaceURI), localNameSegment, WebKitNative.stringLength(localName),
                        resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ATTRIBUTE_NS.invokeExact(peer, namespaceURISegment,
                            WebKitNative.stringLength(namespaceURI), localNameSegment,
                            WebKitNative.stringLength(localName), resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAttributeNS(long peer, String namespaceURI, String qualifiedName, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment namespaceURISegment = WebKitNative.allocString(arena, namespaceURI);
            MemorySegment qualifiedNameSegment = WebKitNative.allocString(arena, qualifiedName);
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ATTRIBUTE_NS.invokeExact(peer, namespaceURISegment, WebKitNative.stringLength(namespaceURI),
                        qualifiedNameSegment, WebKitNative.stringLength(qualifiedName), valueSegment,
                        WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
    }

    static void removeAttributeNS(long peer, String namespaceURI, String localName) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment namespaceURISegment = WebKitNative.allocString(arena, namespaceURI);
            MemorySegment localNameSegment = WebKitNative.allocString(arena, localName);
            try {
                REMOVE_ATTRIBUTE_NS.invokeExact(peer, namespaceURISegment, WebKitNative.stringLength(namespaceURI),
                        localNameSegment, WebKitNative.stringLength(localName));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static long getElementsByTagNameNS(long peer, String namespaceURI, String localName) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment namespaceURISegment = WebKitNative.allocString(arena, namespaceURI);
            MemorySegment localNameSegment = WebKitNative.allocString(arena, localName);
            try {
                result = (long) GET_ELEMENTS_BY_TAG_NAME_NS.invokeExact(peer, namespaceURISegment,
                        WebKitNative.stringLength(namespaceURI), localNameSegment,
                        WebKitNative.stringLength(localName));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result;
    }

    static long getAttributeNodeNS(long peer, String namespaceURI, String localName) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment namespaceURISegment = WebKitNative.allocString(arena, namespaceURI);
            MemorySegment localNameSegment = WebKitNative.allocString(arena, localName);
            try {
                result = (long) GET_ATTRIBUTE_NODE_NS.invokeExact(peer, namespaceURISegment,
                        WebKitNative.stringLength(namespaceURI), localNameSegment,
                        WebKitNative.stringLength(localName));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result;
    }

    static long setAttributeNodeNS(long peer, long newAttr) {
        long result;
        try {
            result = (long) SET_ATTRIBUTE_NODE_NS.invokeExact(peer, newAttr);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static boolean hasAttribute(long peer, String name) {
        int result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment nameSegment = WebKitNative.allocString(arena, name);
            try {
                result = (int) HAS_ATTRIBUTE.invokeExact(peer, nameSegment, WebKitNative.stringLength(name));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result != 0;
    }

    static boolean hasAttributeNS(long peer, String namespaceURI, String localName) {
        int result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment namespaceURISegment = WebKitNative.allocString(arena, namespaceURI);
            MemorySegment localNameSegment = WebKitNative.allocString(arena, localName);
            try {
                result = (int) HAS_ATTRIBUTE_NS.invokeExact(peer, namespaceURISegment,
                        WebKitNative.stringLength(namespaceURI), localNameSegment,
                        WebKitNative.stringLength(localName));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result != 0;
    }

    static void focus(long peer) {
        try {
            FOCUS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void blur(long peer) {
        try {
            BLUR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void scrollIntoView(long peer, boolean alignWithTop) {
        try {
            SCROLL_INTO_VIEW.invokeExact(peer, alignWithTop ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void scrollIntoViewIfNeeded(long peer, boolean centerIfNeeded) {
        try {
            SCROLL_INTO_VIEW_IF_NEEDED.invokeExact(peer, centerIfNeeded ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getElementsByClassName(long peer, String name) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment nameSegment = WebKitNative.allocString(arena, name);
            try {
                result = (long) GET_ELEMENTS_BY_CLASS_NAME.invokeExact(peer, nameSegment,
                        WebKitNative.stringLength(name));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result;
    }

    static boolean matches(long peer, String selectors) {
        int result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment selectorsSegment = WebKitNative.allocString(arena, selectors);
            try {
                result = (int) MATCHES.invokeExact(peer, selectorsSegment, WebKitNative.stringLength(selectors));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result != 0;
    }

    static long closest(long peer, String selectors) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment selectorsSegment = WebKitNative.allocString(arena, selectors);
            try {
                result = (long) CLOSEST.invokeExact(peer, selectorsSegment, WebKitNative.stringLength(selectors));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result;
    }

    static boolean webkitMatchesSelector(long peer, String selectors) {
        int result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment selectorsSegment = WebKitNative.allocString(arena, selectors);
            try {
                result = (int) WEBKIT_MATCHES_SELECTOR.invokeExact(peer, selectorsSegment,
                        WebKitNative.stringLength(selectors));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result != 0;
    }

    static void webkitRequestFullScreen(long peer, short flags) {
        try {
            WEBKIT_REQUEST_FULL_SCREEN.invokeExact(peer, flags);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void webkitRequestFullscreen(long peer) {
        try {
            WEBKIT_REQUEST_FULLSCREEN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void remove(long peer) {
        try {
            REMOVE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static long querySelector(long peer, String selectors) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment selectorsSegment = WebKitNative.allocString(arena, selectors);
            try {
                result = (long) QUERY_SELECTOR.invokeExact(peer, selectorsSegment,
                        WebKitNative.stringLength(selectors));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result;
    }

    static long querySelectorAll(long peer, String selectors) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment selectorsSegment = WebKitNative.allocString(arena, selectors);
            try {
                result = (long) QUERY_SELECTOR_ALL.invokeExact(peer, selectorsSegment,
                        WebKitNative.stringLength(selectors));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result;
    }
}
