/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * FFM facade for the {@code wkj_dom_Event_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link EventImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class EventNative {

    private static final MethodHandle DISPOSE = WebKitNative.downcall("wkj_dom_Event_dispose",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle GET_CPP_TYPE = WebKitNative.downcall("wkj_dom_Event_getCPPType",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_TYPE = WebKitNative.downcall("wkj_dom_Event_getType",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_TARGET = WebKitNative.downcall("wkj_dom_Event_getTarget",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_CURRENT_TARGET = WebKitNative.downcall("wkj_dom_Event_getCurrentTarget",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_EVENT_PHASE = WebKitNative.downcall("wkj_dom_Event_getEventPhase",
            FunctionDescriptor.of(JAVA_SHORT, JAVA_LONG));
    private static final MethodHandle GET_BUBBLES = WebKitNative.downcall("wkj_dom_Event_getBubbles",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_CANCELABLE = WebKitNative.downcall("wkj_dom_Event_getCancelable",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_TIME_STAMP = WebKitNative.downcall("wkj_dom_Event_getTimeStamp",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_DEFAULT_PREVENTED = WebKitNative.downcall("wkj_dom_Event_getDefaultPrevented",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_IS_TRUSTED = WebKitNative.downcall("wkj_dom_Event_getIsTrusted",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SRC_ELEMENT = WebKitNative.downcall("wkj_dom_Event_getSrcElement",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_RETURN_VALUE = WebKitNative.downcall("wkj_dom_Event_getReturnValue",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_RETURN_VALUE = WebKitNative.downcall("wkj_dom_Event_setReturnValue",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_CANCEL_BUBBLE = WebKitNative.downcall("wkj_dom_Event_getCancelBubble",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_CANCEL_BUBBLE = WebKitNative.downcall("wkj_dom_Event_setCancelBubble",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle STOP_PROPAGATION = WebKitNative.downcall("wkj_dom_Event_stopPropagation",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle PREVENT_DEFAULT = WebKitNative.downcall("wkj_dom_Event_preventDefault",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle INIT_EVENT = WebKitNative.downcall("wkj_dom_Event_initEvent",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT));
    private static final MethodHandle STOP_IMMEDIATE_PROPAGATION = WebKitNative.downcall(
            "wkj_dom_Event_stopImmediatePropagation", FunctionDescriptor.ofVoid(JAVA_LONG));

    private EventNative() {
    }

    static void dispose(long peer) {
        try {
            DISPOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getCPPType(long peer) {
        try {
            return (int) GET_CPP_TYPE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getType(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_TYPE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_TYPE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static long getTarget(long peer) {
        try {
            return (long) GET_TARGET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getCurrentTarget(long peer) {
        try {
            return (long) GET_CURRENT_TARGET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static short getEventPhase(long peer) {
        try {
            return (short) GET_EVENT_PHASE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getBubbles(long peer) {
        try {
            return (int) GET_BUBBLES.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getCancelable(long peer) {
        try {
            return (int) GET_CANCELABLE.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getTimeStamp(long peer) {
        try {
            return (long) GET_TIME_STAMP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getDefaultPrevented(long peer) {
        try {
            return (int) GET_DEFAULT_PREVENTED.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getIsTrusted(long peer) {
        try {
            return (int) GET_IS_TRUSTED.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getSrcElement(long peer) {
        try {
            return (long) GET_SRC_ELEMENT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getReturnValue(long peer) {
        try {
            return (int) GET_RETURN_VALUE.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setReturnValue(long peer, boolean value) {
        try {
            SET_RETURN_VALUE.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getCancelBubble(long peer) {
        try {
            return (int) GET_CANCEL_BUBBLE.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setCancelBubble(long peer, boolean value) {
        try {
            SET_CANCEL_BUBBLE.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void stopPropagation(long peer) {
        try {
            STOP_PROPAGATION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void preventDefault(long peer) {
        try {
            PREVENT_DEFAULT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void initEvent(long peer, String eventTypeArg, boolean canBubbleArg, boolean cancelableArg) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment eventTypeArgSegment = WebKitNative.allocString(arena, eventTypeArg);
            try {
                INIT_EVENT.invokeExact(peer, eventTypeArgSegment, WebKitNative.stringLength(eventTypeArg),
                        canBubbleArg ? 1 : 0, cancelableArg ? 1 : 0);
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void stopImmediatePropagation(long peer) {
        try {
            STOP_IMMEDIATE_PROPAGATION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }
}
