/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_HTMLTableCellElement_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link HTMLTableCellElementImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class HTMLTableCellElementNative {

    private static final MethodHandle GET_CELL_INDEX = WebKitNative.downcall(
            "wkj_dom_HTMLTableCellElement_getCellIndex", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_ALIGN = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getAlign",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ALIGN = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setAlign",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_AXIS = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getAxis",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_AXIS = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setAxis",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_BG_COLOR = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getBgColor",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_BG_COLOR = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setBgColor",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_CH = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getCh",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_CH = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setCh",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_CH_OFF = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getChOff",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_CH_OFF = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setChOff",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_COL_SPAN = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getColSpan",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_COL_SPAN = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setColSpan",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_ROW_SPAN = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getRowSpan",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_ROW_SPAN = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setRowSpan",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_HEADERS = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getHeaders",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_HEADERS = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setHeaders",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_HEIGHT = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getHeight",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_HEIGHT = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setHeight",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_NO_WRAP = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getNoWrap",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_NO_WRAP = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setNoWrap",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_V_ALIGN = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getVAlign",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_V_ALIGN = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setVAlign",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_WIDTH = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getWidth",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_WIDTH = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setWidth",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ABBR = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getAbbr",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ABBR = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setAbbr",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_SCOPE = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_getScope",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_SCOPE = WebKitNative.downcall("wkj_dom_HTMLTableCellElement_setScope",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));

    private HTMLTableCellElementNative() {
    }

    static int getCellIndex(long peer) {
        try {
            return (int) GET_CELL_INDEX.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getAlign(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ALIGN.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ALIGN.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAlign(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ALIGN.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getAxis(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_AXIS.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_AXIS.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAxis(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_AXIS.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getBgColor(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_BG_COLOR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_BG_COLOR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setBgColor(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_BG_COLOR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getCh(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_CH.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_CH.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setCh(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_CH.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getChOff(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_CH_OFF.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_CH_OFF.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setChOff(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_CH_OFF.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static int getColSpan(long peer) {
        try {
            return (int) GET_COL_SPAN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setColSpan(long peer, int value) {
        try {
            SET_COL_SPAN.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getRowSpan(long peer) {
        try {
            return (int) GET_ROW_SPAN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setRowSpan(long peer, int value) {
        try {
            SET_ROW_SPAN.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getHeaders(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_HEADERS.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_HEADERS.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setHeaders(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_HEADERS.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getHeight(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_HEIGHT.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_HEIGHT.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setHeight(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_HEIGHT.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static boolean getNoWrap(long peer) {
        try {
            return (int) GET_NO_WRAP.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setNoWrap(long peer, boolean value) {
        try {
            SET_NO_WRAP.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getVAlign(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_V_ALIGN.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_V_ALIGN.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setVAlign(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_V_ALIGN.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getWidth(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_WIDTH.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_WIDTH.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setWidth(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_WIDTH.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getAbbr(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ABBR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ABBR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAbbr(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ABBR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getScope(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_SCOPE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_SCOPE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setScope(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_SCOPE.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }
}
