/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_HTMLTableElement_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link HTMLTableElementImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class HTMLTableElementNative {

    private static final MethodHandle GET_CAPTION = WebKitNative.downcall("wkj_dom_HTMLTableElement_getCaption",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_CAPTION = WebKitNative.downcall("wkj_dom_HTMLTableElement_setCaption",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_T_HEAD = WebKitNative.downcall("wkj_dom_HTMLTableElement_getTHead",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_T_HEAD = WebKitNative.downcall("wkj_dom_HTMLTableElement_setTHead",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_T_FOOT = WebKitNative.downcall("wkj_dom_HTMLTableElement_getTFoot",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_T_FOOT = WebKitNative.downcall("wkj_dom_HTMLTableElement_setTFoot",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ROWS = WebKitNative.downcall("wkj_dom_HTMLTableElement_getRows",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_T_BODIES = WebKitNative.downcall("wkj_dom_HTMLTableElement_getTBodies",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ALIGN = WebKitNative.downcall("wkj_dom_HTMLTableElement_getAlign",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ALIGN = WebKitNative.downcall("wkj_dom_HTMLTableElement_setAlign",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_BG_COLOR = WebKitNative.downcall("wkj_dom_HTMLTableElement_getBgColor",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_BG_COLOR = WebKitNative.downcall("wkj_dom_HTMLTableElement_setBgColor",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_BORDER = WebKitNative.downcall("wkj_dom_HTMLTableElement_getBorder",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_BORDER = WebKitNative.downcall("wkj_dom_HTMLTableElement_setBorder",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_CELL_PADDING = WebKitNative.downcall(
            "wkj_dom_HTMLTableElement_getCellPadding",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_CELL_PADDING = WebKitNative.downcall(
            "wkj_dom_HTMLTableElement_setCellPadding", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_CELL_SPACING = WebKitNative.downcall(
            "wkj_dom_HTMLTableElement_getCellSpacing",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_CELL_SPACING = WebKitNative.downcall(
            "wkj_dom_HTMLTableElement_setCellSpacing", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_FRAME = WebKitNative.downcall("wkj_dom_HTMLTableElement_getFrame",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_FRAME = WebKitNative.downcall("wkj_dom_HTMLTableElement_setFrame",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_RULES = WebKitNative.downcall("wkj_dom_HTMLTableElement_getRules",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_RULES = WebKitNative.downcall("wkj_dom_HTMLTableElement_setRules",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_SUMMARY = WebKitNative.downcall("wkj_dom_HTMLTableElement_getSummary",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_SUMMARY = WebKitNative.downcall("wkj_dom_HTMLTableElement_setSummary",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_WIDTH = WebKitNative.downcall("wkj_dom_HTMLTableElement_getWidth",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_WIDTH = WebKitNative.downcall("wkj_dom_HTMLTableElement_setWidth",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle CREATE_T_HEAD = WebKitNative.downcall("wkj_dom_HTMLTableElement_createTHead",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle DELETE_T_HEAD = WebKitNative.downcall("wkj_dom_HTMLTableElement_deleteTHead",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle CREATE_T_FOOT = WebKitNative.downcall("wkj_dom_HTMLTableElement_createTFoot",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle DELETE_T_FOOT = WebKitNative.downcall("wkj_dom_HTMLTableElement_deleteTFoot",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle CREATE_T_BODY = WebKitNative.downcall("wkj_dom_HTMLTableElement_createTBody",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle CREATE_CAPTION = WebKitNative.downcall("wkj_dom_HTMLTableElement_createCaption",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle DELETE_CAPTION = WebKitNative.downcall("wkj_dom_HTMLTableElement_deleteCaption",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle INSERT_ROW = WebKitNative.downcall("wkj_dom_HTMLTableElement_insertRow",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT));
    private static final MethodHandle DELETE_ROW = WebKitNative.downcall("wkj_dom_HTMLTableElement_deleteRow",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));

    private HTMLTableElementNative() {
    }

    static long getCaption(long peer) {
        try {
            return (long) GET_CAPTION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setCaption(long peer, long value) {
        try {
            SET_CAPTION.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getTHead(long peer) {
        try {
            return (long) GET_T_HEAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setTHead(long peer, long value) {
        try {
            SET_T_HEAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getTFoot(long peer) {
        try {
            return (long) GET_T_FOOT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setTFoot(long peer, long value) {
        try {
            SET_T_FOOT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getRows(long peer) {
        try {
            return (long) GET_ROWS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getTBodies(long peer) {
        try {
            return (long) GET_T_BODIES.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getAlign(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ALIGN.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ALIGN.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAlign(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ALIGN.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getBgColor(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_BG_COLOR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_BG_COLOR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setBgColor(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_BG_COLOR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getBorder(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_BORDER.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_BORDER.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setBorder(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_BORDER.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getCellPadding(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_CELL_PADDING.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_CELL_PADDING.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setCellPadding(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_CELL_PADDING.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getCellSpacing(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_CELL_SPACING.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_CELL_SPACING.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setCellSpacing(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_CELL_SPACING.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getFrame(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_FRAME.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_FRAME.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setFrame(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_FRAME.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getRules(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_RULES.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_RULES.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setRules(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_RULES.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getSummary(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_SUMMARY.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_SUMMARY.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setSummary(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_SUMMARY.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getWidth(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_WIDTH.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_WIDTH.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setWidth(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_WIDTH.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static long createTHead(long peer) {
        try {
            return (long) CREATE_T_HEAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void deleteTHead(long peer) {
        try {
            DELETE_T_HEAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long createTFoot(long peer) {
        try {
            return (long) CREATE_T_FOOT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void deleteTFoot(long peer) {
        try {
            DELETE_T_FOOT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long createTBody(long peer) {
        try {
            return (long) CREATE_T_BODY.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long createCaption(long peer) {
        try {
            return (long) CREATE_CAPTION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void deleteCaption(long peer) {
        try {
            DELETE_CAPTION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long insertRow(long peer, int index) {
        long result;
        try {
            result = (long) INSERT_ROW.invokeExact(peer, index);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static void deleteRow(long peer, int index) {
        try {
            DELETE_ROW.invokeExact(peer, index);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }
}
