/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_HTMLFrameSetElement_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link HTMLFrameSetElementImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class HTMLFrameSetElementNative {

    private static final MethodHandle GET_COLS = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getCols",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_COLS = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setCols",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ROWS = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getRows",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ROWS = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setRows",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ONBLUR = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnblur",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBLUR = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnblur",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONERROR = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnerror",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONERROR = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnerror",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONFOCUS = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnfocus",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONFOCUS = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnfocus",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONFOCUSIN = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnfocusin",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONFOCUSIN = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnfocusin",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONFOCUSOUT = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_getOnfocusout", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONFOCUSOUT = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_setOnfocusout", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONLOAD = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnload",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONLOAD = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnload",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONRESIZE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnresize",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONRESIZE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnresize",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSCROLL = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnscroll",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSCROLL = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnscroll",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONBEFOREUNLOAD = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_getOnbeforeunload", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONBEFOREUNLOAD = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_setOnbeforeunload", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONHASHCHANGE = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_getOnhashchange", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONHASHCHANGE = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_setOnhashchange", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONMESSAGE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnmessage",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONMESSAGE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnmessage",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONOFFLINE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnoffline",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONOFFLINE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnoffline",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONONLINE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnonline",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONONLINE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnonline",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPAGEHIDE = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_getOnpagehide", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPAGEHIDE = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_setOnpagehide", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPAGESHOW = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_getOnpageshow", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPAGESHOW = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_setOnpageshow", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONPOPSTATE = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_getOnpopstate", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONPOPSTATE = WebKitNative.downcall(
            "wkj_dom_HTMLFrameSetElement_setOnpopstate", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONSTORAGE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnstorage",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONSTORAGE = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnstorage",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ONUNLOAD = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_getOnunload",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_ONUNLOAD = WebKitNative.downcall("wkj_dom_HTMLFrameSetElement_setOnunload",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));

    private HTMLFrameSetElementNative() {
    }

    static String getCols(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_COLS.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_COLS.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setCols(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_COLS.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getRows(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ROWS.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ROWS.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setRows(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ROWS.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static long getOnblur(long peer) {
        try {
            return (long) GET_ONBLUR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnblur(long peer, long value) {
        try {
            SET_ONBLUR.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnerror(long peer) {
        try {
            return (long) GET_ONERROR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnerror(long peer, long value) {
        try {
            SET_ONERROR.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnfocus(long peer) {
        try {
            return (long) GET_ONFOCUS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnfocus(long peer, long value) {
        try {
            SET_ONFOCUS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnfocusin(long peer) {
        try {
            return (long) GET_ONFOCUSIN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnfocusin(long peer, long value) {
        try {
            SET_ONFOCUSIN.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnfocusout(long peer) {
        try {
            return (long) GET_ONFOCUSOUT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnfocusout(long peer, long value) {
        try {
            SET_ONFOCUSOUT.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnload(long peer) {
        try {
            return (long) GET_ONLOAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnload(long peer, long value) {
        try {
            SET_ONLOAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnresize(long peer) {
        try {
            return (long) GET_ONRESIZE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnresize(long peer, long value) {
        try {
            SET_ONRESIZE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnscroll(long peer) {
        try {
            return (long) GET_ONSCROLL.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnscroll(long peer, long value) {
        try {
            SET_ONSCROLL.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnbeforeunload(long peer) {
        try {
            return (long) GET_ONBEFOREUNLOAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnbeforeunload(long peer, long value) {
        try {
            SET_ONBEFOREUNLOAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnhashchange(long peer) {
        try {
            return (long) GET_ONHASHCHANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnhashchange(long peer, long value) {
        try {
            SET_ONHASHCHANGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnmessage(long peer) {
        try {
            return (long) GET_ONMESSAGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnmessage(long peer, long value) {
        try {
            SET_ONMESSAGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnoffline(long peer) {
        try {
            return (long) GET_ONOFFLINE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnoffline(long peer, long value) {
        try {
            SET_ONOFFLINE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnonline(long peer) {
        try {
            return (long) GET_ONONLINE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnonline(long peer, long value) {
        try {
            SET_ONONLINE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpagehide(long peer) {
        try {
            return (long) GET_ONPAGEHIDE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpagehide(long peer, long value) {
        try {
            SET_ONPAGEHIDE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpageshow(long peer) {
        try {
            return (long) GET_ONPAGESHOW.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpageshow(long peer, long value) {
        try {
            SET_ONPAGESHOW.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnpopstate(long peer) {
        try {
            return (long) GET_ONPOPSTATE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnpopstate(long peer, long value) {
        try {
            SET_ONPOPSTATE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnstorage(long peer) {
        try {
            return (long) GET_ONSTORAGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnstorage(long peer, long value) {
        try {
            SET_ONSTORAGE.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getOnunload(long peer) {
        try {
            return (long) GET_ONUNLOAD.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setOnunload(long peer, long value) {
        try {
            SET_ONUNLOAD.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }
}
