/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_HTMLDocument_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link HTMLDocumentImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class HTMLDocumentNative {

    private static final MethodHandle GET_EMBEDS = WebKitNative.downcall("wkj_dom_HTMLDocument_getEmbeds",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_PLUGINS = WebKitNative.downcall("wkj_dom_HTMLDocument_getPlugins",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_SCRIPTS = WebKitNative.downcall("wkj_dom_HTMLDocument_getScripts",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_DIR = WebKitNative.downcall("wkj_dom_HTMLDocument_getDir",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_DIR = WebKitNative.downcall("wkj_dom_HTMLDocument_setDir",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_DESIGN_MODE = WebKitNative.downcall("wkj_dom_HTMLDocument_getDesignMode",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_DESIGN_MODE = WebKitNative.downcall("wkj_dom_HTMLDocument_setDesignMode",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_COMPAT_MODE = WebKitNative.downcall("wkj_dom_HTMLDocument_getCompatMode",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_BG_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_getBgColor",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_BG_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_setBgColor",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_FG_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_getFgColor",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_FG_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_setFgColor",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ALINK_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_getAlinkColor",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ALINK_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_setAlinkColor",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_LINK_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_getLinkColor",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_LINK_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_setLinkColor",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_VLINK_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_getVlinkColor",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_VLINK_COLOR = WebKitNative.downcall("wkj_dom_HTMLDocument_setVlinkColor",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle OPEN = WebKitNative.downcall("wkj_dom_HTMLDocument_open",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle CLOSE = WebKitNative.downcall("wkj_dom_HTMLDocument_close",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle WRITE = WebKitNative.downcall("wkj_dom_HTMLDocument_write",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle WRITELN = WebKitNative.downcall("wkj_dom_HTMLDocument_writeln",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle CLEAR = WebKitNative.downcall("wkj_dom_HTMLDocument_clear",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle CAPTURE_EVENTS = WebKitNative.downcall("wkj_dom_HTMLDocument_captureEvents",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle RELEASE_EVENTS = WebKitNative.downcall("wkj_dom_HTMLDocument_releaseEvents",
            FunctionDescriptor.ofVoid(JAVA_LONG));

    private HTMLDocumentNative() {
    }

    static long getEmbeds(long peer) {
        try {
            return (long) GET_EMBEDS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getPlugins(long peer) {
        try {
            return (long) GET_PLUGINS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getScripts(long peer) {
        try {
            return (long) GET_SCRIPTS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getDir(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_DIR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_DIR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setDir(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_DIR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getDesignMode(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_DESIGN_MODE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_DESIGN_MODE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setDesignMode(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_DESIGN_MODE.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getCompatMode(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_COMPAT_MODE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_COMPAT_MODE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static String getBgColor(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_BG_COLOR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_BG_COLOR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setBgColor(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_BG_COLOR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getFgColor(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_FG_COLOR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_FG_COLOR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setFgColor(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_FG_COLOR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getAlinkColor(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ALINK_COLOR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ALINK_COLOR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAlinkColor(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ALINK_COLOR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getLinkColor(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_LINK_COLOR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_LINK_COLOR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setLinkColor(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_LINK_COLOR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getVlinkColor(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_VLINK_COLOR.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_VLINK_COLOR.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setVlinkColor(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_VLINK_COLOR.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void open(long peer) {
        try {
            OPEN.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void close(long peer) {
        try {
            CLOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void write(long peer, String text) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment textSegment = WebKitNative.allocString(arena, text);
            try {
                WRITE.invokeExact(peer, textSegment, WebKitNative.stringLength(text));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void writeln(long peer, String text) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment textSegment = WebKitNative.allocString(arena, text);
            try {
                WRITELN.invokeExact(peer, textSegment, WebKitNative.stringLength(text));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void clear(long peer) {
        try {
            CLEAR.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void captureEvents(long peer) {
        try {
            CAPTURE_EVENTS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void releaseEvents(long peer) {
        try {
            RELEASE_EVENTS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }
}
