/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_HTMLTextAreaElement_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link HTMLTextAreaElementImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class HTMLTextAreaElementNative {

    private static final MethodHandle GET_AUTOFOCUS = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getAutofocus",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_AUTOFOCUS = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setAutofocus",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_DIR_NAME = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getDirName",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_DIR_NAME = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setDirName",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_DISABLED = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getDisabled",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_DISABLED = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setDisabled",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_FORM = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getForm",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_MAX_LENGTH = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getMaxLength",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_MAX_LENGTH = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setMaxLength",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_NAME = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getName",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_NAME = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setName",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_PLACEHOLDER = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getPlaceholder",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_PLACEHOLDER = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_setPlaceholder", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_READ_ONLY = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getReadOnly",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_READ_ONLY = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setReadOnly",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_REQUIRED = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getRequired",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_REQUIRED = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setRequired",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_ROWS = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getRows",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_ROWS = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setRows",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_COLS = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getCols",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_COLS = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setCols",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_WRAP = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getWrap",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_WRAP = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setWrap",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_TYPE = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getType",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_DEFAULT_VALUE = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getDefaultValue",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_DEFAULT_VALUE = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_setDefaultValue", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_VALUE = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getValue",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_VALUE = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setValue",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_TEXT_LENGTH = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getTextLength", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_WILL_VALIDATE = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getWillValidate", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_VALIDATION_MESSAGE = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getValidationMessage",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_LABELS = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getLabels",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_SELECTION_START = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getSelectionStart", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_SELECTION_START = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_setSelectionStart", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_SELECTION_END = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getSelectionEnd", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_SELECTION_END = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_setSelectionEnd", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_SELECTION_DIRECTION = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getSelectionDirection",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_SELECTION_DIRECTION = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_setSelectionDirection",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_ACCESS_KEY = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_getAccessKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ACCESS_KEY = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setAccessKey",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_AUTOCOMPLETE = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_getAutocomplete",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle CHECK_VALIDITY = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_checkValidity", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_CUSTOM_VALIDITY = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_setCustomValidity", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle SELECT = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_select",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle SET_RANGE_TEXT = WebKitNative.downcall("wkj_dom_HTMLTextAreaElement_setRangeText",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle SET_RANGE_TEXT_EX = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_setRangeTextEx",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, ADDRESS, JAVA_INT));
    private static final MethodHandle SET_SELECTION_RANGE = WebKitNative.downcall(
            "wkj_dom_HTMLTextAreaElement_setSelectionRange",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT, JAVA_INT, ADDRESS, JAVA_INT));

    private HTMLTextAreaElementNative() {
    }

    static boolean getAutofocus(long peer) {
        try {
            return (int) GET_AUTOFOCUS.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setAutofocus(long peer, boolean value) {
        try {
            SET_AUTOFOCUS.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getDirName(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_DIR_NAME.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_DIR_NAME.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setDirName(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_DIR_NAME.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static boolean getDisabled(long peer) {
        try {
            return (int) GET_DISABLED.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setDisabled(long peer, boolean value) {
        try {
            SET_DISABLED.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getForm(long peer) {
        try {
            return (long) GET_FORM.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getMaxLength(long peer) {
        try {
            return (int) GET_MAX_LENGTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setMaxLength(long peer, int value) {
        try {
            SET_MAX_LENGTH.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getName(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_NAME.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_NAME.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setName(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_NAME.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getPlaceholder(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_PLACEHOLDER.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_PLACEHOLDER.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setPlaceholder(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_PLACEHOLDER.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static boolean getReadOnly(long peer) {
        try {
            return (int) GET_READ_ONLY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setReadOnly(long peer, boolean value) {
        try {
            SET_READ_ONLY.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getRequired(long peer) {
        try {
            return (int) GET_REQUIRED.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setRequired(long peer, boolean value) {
        try {
            SET_REQUIRED.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getRows(long peer) {
        try {
            return (int) GET_ROWS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setRows(long peer, int value) {
        try {
            SET_ROWS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getCols(long peer) {
        try {
            return (int) GET_COLS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setCols(long peer, int value) {
        try {
            SET_COLS.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getWrap(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_WRAP.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_WRAP.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setWrap(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_WRAP.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getType(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_TYPE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_TYPE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static String getDefaultValue(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_DEFAULT_VALUE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_DEFAULT_VALUE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setDefaultValue(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_DEFAULT_VALUE.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getValue(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_VALUE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_VALUE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setValue(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_VALUE.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static int getTextLength(long peer) {
        try {
            return (int) GET_TEXT_LENGTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getWillValidate(long peer) {
        try {
            return (int) GET_WILL_VALIDATE.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getValidationMessage(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_VALIDATION_MESSAGE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY,
                        resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_VALIDATION_MESSAGE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static long getLabels(long peer) {
        try {
            return (long) GET_LABELS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getSelectionStart(long peer) {
        try {
            return (int) GET_SELECTION_START.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setSelectionStart(long peer, int value) {
        try {
            SET_SELECTION_START.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getSelectionEnd(long peer) {
        try {
            return (int) GET_SELECTION_END.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setSelectionEnd(long peer, int value) {
        try {
            SET_SELECTION_END.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getSelectionDirection(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_SELECTION_DIRECTION.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY,
                        resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_SELECTION_DIRECTION.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setSelectionDirection(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_SELECTION_DIRECTION.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getAccessKey(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ACCESS_KEY.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ACCESS_KEY.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAccessKey(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ACCESS_KEY.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getAutocomplete(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_AUTOCOMPLETE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_AUTOCOMPLETE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static boolean checkValidity(long peer) {
        try {
            return (int) CHECK_VALIDITY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setCustomValidity(long peer, String error) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment errorSegment = WebKitNative.allocString(arena, error);
            try {
                SET_CUSTOM_VALIDITY.invokeExact(peer, errorSegment, WebKitNative.stringLength(error));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void select(long peer) {
        try {
            SELECT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setRangeText(long peer, String replacement) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment replacementSegment = WebKitNative.allocString(arena, replacement);
            try {
                SET_RANGE_TEXT.invokeExact(peer, replacementSegment, WebKitNative.stringLength(replacement));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
    }

    static void setRangeTextEx(long peer, String replacement, int start, int end, String selectionMode) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment replacementSegment = WebKitNative.allocString(arena, replacement);
            MemorySegment selectionModeSegment = WebKitNative.allocString(arena, selectionMode);
            try {
                SET_RANGE_TEXT_EX.invokeExact(peer, replacementSegment, WebKitNative.stringLength(replacement), start,
                        end, selectionModeSegment, WebKitNative.stringLength(selectionMode));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
    }

    static void setSelectionRange(long peer, int start, int end, String direction) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment directionSegment = WebKitNative.allocString(arena, direction);
            try {
                SET_SELECTION_RANGE.invokeExact(peer, start, end, directionSegment,
                        WebKitNative.stringLength(direction));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }
}
