/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_HTMLOptionsCollection_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link HTMLOptionsCollectionImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class HTMLOptionsCollectionNative {

    private static final MethodHandle GET_SELECTED_INDEX = WebKitNative.downcall(
            "wkj_dom_HTMLOptionsCollection_getSelectedIndex", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_SELECTED_INDEX = WebKitNative.downcall(
            "wkj_dom_HTMLOptionsCollection_setSelectedIndex", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_LENGTH = WebKitNative.downcall("wkj_dom_HTMLOptionsCollection_getLength",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_LENGTH = WebKitNative.downcall("wkj_dom_HTMLOptionsCollection_setLength",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle NAMED_ITEM = WebKitNative.downcall("wkj_dom_HTMLOptionsCollection_namedItem",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle ADD = WebKitNative.downcall("wkj_dom_HTMLOptionsCollection_add",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_INT));
    private static final MethodHandle ITEM = WebKitNative.downcall("wkj_dom_HTMLOptionsCollection_item",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT));

    private HTMLOptionsCollectionNative() {
    }

    static int getSelectedIndex(long peer) {
        try {
            return (int) GET_SELECTED_INDEX.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setSelectedIndex(long peer, int value) {
        try {
            SET_SELECTED_INDEX.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getLength(long peer) {
        try {
            return (int) GET_LENGTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setLength(long peer, int value) {
        try {
            SET_LENGTH.invokeExact(peer, value);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long namedItem(long peer, String name) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment nameSegment = WebKitNative.allocString(arena, name);
            try {
                result = (long) NAMED_ITEM.invokeExact(peer, nameSegment, WebKitNative.stringLength(name));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result;
    }

    static void add(long peer, long option, int index) {
        try {
            ADD.invokeExact(peer, option, index);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static long item(long peer, int index) {
        try {
            return (long) ITEM.invokeExact(peer, index);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }
}
