/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_HTMLButtonElement_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link HTMLButtonElementImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class HTMLButtonElementNative {

    private static final MethodHandle GET_AUTOFOCUS = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getAutofocus",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_AUTOFOCUS = WebKitNative.downcall("wkj_dom_HTMLButtonElement_setAutofocus",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_DISABLED = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getDisabled",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_DISABLED = WebKitNative.downcall("wkj_dom_HTMLButtonElement_setDisabled",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_FORM = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getForm",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_FORM_ACTION = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getFormAction",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_FORM_ENCTYPE = WebKitNative.downcall(
            "wkj_dom_HTMLButtonElement_getFormEnctype",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_FORM_METHOD = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getFormMethod",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_TYPE = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getType",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_FORM_NO_VALIDATE = WebKitNative.downcall(
            "wkj_dom_HTMLButtonElement_getFormNoValidate", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_FORM_NO_VALIDATE = WebKitNative.downcall(
            "wkj_dom_HTMLButtonElement_setFormNoValidate", FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle GET_FORM_TARGET = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getFormTarget",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_FORM_TARGET = WebKitNative.downcall("wkj_dom_HTMLButtonElement_setFormTarget",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_NAME = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getName",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_NAME = WebKitNative.downcall("wkj_dom_HTMLButtonElement_setName",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_VALUE = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getValue",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_VALUE = WebKitNative.downcall("wkj_dom_HTMLButtonElement_setValue",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle GET_WILL_VALIDATE = WebKitNative.downcall(
            "wkj_dom_HTMLButtonElement_getWillValidate", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_VALIDATION_MESSAGE = WebKitNative.downcall(
            "wkj_dom_HTMLButtonElement_getValidationMessage",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_LABELS = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getLabels",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_ACCESS_KEY = WebKitNative.downcall("wkj_dom_HTMLButtonElement_getAccessKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_ACCESS_KEY = WebKitNative.downcall("wkj_dom_HTMLButtonElement_setAccessKey",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle CHECK_VALIDITY = WebKitNative.downcall("wkj_dom_HTMLButtonElement_checkValidity",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle SET_CUSTOM_VALIDITY = WebKitNative.downcall(
            "wkj_dom_HTMLButtonElement_setCustomValidity", FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle CLICK = WebKitNative.downcall("wkj_dom_HTMLButtonElement_click",
            FunctionDescriptor.ofVoid(JAVA_LONG));

    private HTMLButtonElementNative() {
    }

    static boolean getAutofocus(long peer) {
        try {
            return (int) GET_AUTOFOCUS.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setAutofocus(long peer, boolean value) {
        try {
            SET_AUTOFOCUS.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getDisabled(long peer) {
        try {
            return (int) GET_DISABLED.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setDisabled(long peer, boolean value) {
        try {
            SET_DISABLED.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getForm(long peer) {
        try {
            return (long) GET_FORM.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getFormAction(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_FORM_ACTION.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_FORM_ACTION.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static String getFormEnctype(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_FORM_ENCTYPE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_FORM_ENCTYPE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static String getFormMethod(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_FORM_METHOD.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_FORM_METHOD.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static String getType(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_TYPE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_TYPE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static boolean getFormNoValidate(long peer) {
        try {
            return (int) GET_FORM_NO_VALIDATE.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setFormNoValidate(long peer, boolean value) {
        try {
            SET_FORM_NO_VALIDATE.invokeExact(peer, value ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getFormTarget(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_FORM_TARGET.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_FORM_TARGET.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setFormTarget(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_FORM_TARGET.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getName(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_NAME.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_NAME.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setName(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_NAME.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static String getValue(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_VALUE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_VALUE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setValue(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_VALUE.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static boolean getWillValidate(long peer) {
        try {
            return (int) GET_WILL_VALIDATE.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getValidationMessage(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_VALIDATION_MESSAGE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY,
                        resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_VALIDATION_MESSAGE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static long getLabels(long peer) {
        try {
            return (long) GET_LABELS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getAccessKey(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_ACCESS_KEY.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_ACCESS_KEY.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setAccessKey(long peer, String value) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment valueSegment = WebKitNative.allocString(arena, value);
            try {
                SET_ACCESS_KEY.invokeExact(peer, valueSegment, WebKitNative.stringLength(value));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static boolean checkValidity(long peer) {
        try {
            return (int) CHECK_VALIDITY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void setCustomValidity(long peer, String error) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment errorSegment = WebKitNative.allocString(arena, error);
            try {
                SET_CUSTOM_VALIDITY.invokeExact(peer, errorSegment, WebKitNative.stringLength(error));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void click(long peer) {
        try {
            CLICK.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }
}
