/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_KeyboardEvent_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link KeyboardEventImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class KeyboardEventNative {

    private static final MethodHandle GET_KEY_IDENTIFIER = WebKitNative.downcall(
            "wkj_dom_KeyboardEvent_getKeyIdentifier",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_LOCATION = WebKitNative.downcall("wkj_dom_KeyboardEvent_getLocation",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_KEY_LOCATION = WebKitNative.downcall("wkj_dom_KeyboardEvent_getKeyLocation",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_CTRL_KEY = WebKitNative.downcall("wkj_dom_KeyboardEvent_getCtrlKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SHIFT_KEY = WebKitNative.downcall("wkj_dom_KeyboardEvent_getShiftKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_ALT_KEY = WebKitNative.downcall("wkj_dom_KeyboardEvent_getAltKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_META_KEY = WebKitNative.downcall("wkj_dom_KeyboardEvent_getMetaKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_KEY_CODE = WebKitNative.downcall("wkj_dom_KeyboardEvent_getKeyCode",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_CHAR_CODE = WebKitNative.downcall("wkj_dom_KeyboardEvent_getCharCode",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_MODIFIER_STATE = WebKitNative.downcall(
            "wkj_dom_KeyboardEvent_getModifierState", FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle INIT_KEYBOARD_EVENT = WebKitNative.downcall(
            "wkj_dom_KeyboardEvent_initKeyboardEvent",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT,
                    JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT));
    private static final MethodHandle INIT_KEYBOARD_EVENT_EX = WebKitNative.downcall(
            "wkj_dom_KeyboardEvent_initKeyboardEventEx",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT,
                    JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT));

    private KeyboardEventNative() {
    }

    static String getKeyIdentifier(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_KEY_IDENTIFIER.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY,
                        resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_KEY_IDENTIFIER.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static int getLocation(long peer) {
        try {
            return (int) GET_LOCATION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getKeyLocation(long peer) {
        try {
            return (int) GET_KEY_LOCATION.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getCtrlKey(long peer) {
        try {
            return (int) GET_CTRL_KEY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getShiftKey(long peer) {
        try {
            return (int) GET_SHIFT_KEY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getAltKey(long peer) {
        try {
            return (int) GET_ALT_KEY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getMetaKey(long peer) {
        try {
            return (int) GET_META_KEY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getKeyCode(long peer) {
        try {
            return (int) GET_KEY_CODE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getCharCode(long peer) {
        try {
            return (int) GET_CHAR_CODE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getModifierState(long peer, String keyIdentifierArg) {
        int result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment keyIdentifierArgSegment = WebKitNative.allocString(arena, keyIdentifierArg);
            try {
                result = (int) GET_MODIFIER_STATE.invokeExact(peer, keyIdentifierArgSegment,
                        WebKitNative.stringLength(keyIdentifierArg));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        return result != 0;
    }

    // altGraphKey is accepted for source compatibility and not passed on: wkj_dom_KeyboardEvent_initKeyboardEvent has
    // never taken it.
    static void initKeyboardEvent(long peer, String type, boolean canBubble, boolean cancelable, long view,
            String keyIdentifier, int location, boolean ctrlKey, boolean altKey, boolean shiftKey, boolean metaKey,
            boolean altGraphKey) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment typeSegment = WebKitNative.allocString(arena, type);
            MemorySegment keyIdentifierSegment = WebKitNative.allocString(arena, keyIdentifier);
            try {
                INIT_KEYBOARD_EVENT.invokeExact(peer, typeSegment, WebKitNative.stringLength(type), canBubble ? 1 : 0,
                        cancelable ? 1 : 0, view, keyIdentifierSegment, WebKitNative.stringLength(keyIdentifier),
                        location, ctrlKey ? 1 : 0, altKey ? 1 : 0, shiftKey ? 1 : 0, metaKey ? 1 : 0);
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }

    static void initKeyboardEventEx(long peer, String type, boolean canBubble, boolean cancelable, long view,
            String keyIdentifier, int location, boolean ctrlKey, boolean altKey, boolean shiftKey, boolean metaKey) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment typeSegment = WebKitNative.allocString(arena, type);
            MemorySegment keyIdentifierSegment = WebKitNative.allocString(arena, keyIdentifier);
            try {
                INIT_KEYBOARD_EVENT_EX.invokeExact(peer, typeSegment, WebKitNative.stringLength(type),
                        canBubble ? 1 : 0, cancelable ? 1 : 0, view, keyIdentifierSegment,
                        WebKitNative.stringLength(keyIdentifier), location, ctrlKey ? 1 : 0, altKey ? 1 : 0,
                        shiftKey ? 1 : 0, metaKey ? 1 : 0);
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }
}
