/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * FFM facade for the {@code wkj_dom_MouseEvent_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link MouseEventImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class MouseEventNative {

    private static final MethodHandle GET_SCREEN_X = WebKitNative.downcall("wkj_dom_MouseEvent_getScreenX",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SCREEN_Y = WebKitNative.downcall("wkj_dom_MouseEvent_getScreenY",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_CLIENT_X = WebKitNative.downcall("wkj_dom_MouseEvent_getClientX",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_CLIENT_Y = WebKitNative.downcall("wkj_dom_MouseEvent_getClientY",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_CTRL_KEY = WebKitNative.downcall("wkj_dom_MouseEvent_getCtrlKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SHIFT_KEY = WebKitNative.downcall("wkj_dom_MouseEvent_getShiftKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_ALT_KEY = WebKitNative.downcall("wkj_dom_MouseEvent_getAltKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_META_KEY = WebKitNative.downcall("wkj_dom_MouseEvent_getMetaKey",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_BUTTON = WebKitNative.downcall("wkj_dom_MouseEvent_getButton",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_RELATED_TARGET = WebKitNative.downcall("wkj_dom_MouseEvent_getRelatedTarget",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_OFFSET_X = WebKitNative.downcall("wkj_dom_MouseEvent_getOffsetX",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_OFFSET_Y = WebKitNative.downcall("wkj_dom_MouseEvent_getOffsetY",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_FROM_ELEMENT = WebKitNative.downcall("wkj_dom_MouseEvent_getFromElement",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_TO_ELEMENT = WebKitNative.downcall("wkj_dom_MouseEvent_getToElement",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle INIT_MOUSE_EVENT = WebKitNative.downcall("wkj_dom_MouseEvent_initMouseEvent",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_LONG, JAVA_INT, JAVA_INT,
                    JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_SHORT, JAVA_LONG));

    private MouseEventNative() {
    }

    static int getScreenX(long peer) {
        try {
            return (int) GET_SCREEN_X.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getScreenY(long peer) {
        try {
            return (int) GET_SCREEN_Y.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getClientX(long peer) {
        try {
            return (int) GET_CLIENT_X.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getClientY(long peer) {
        try {
            return (int) GET_CLIENT_Y.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getCtrlKey(long peer) {
        try {
            return (int) GET_CTRL_KEY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getShiftKey(long peer) {
        try {
            return (int) GET_SHIFT_KEY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getAltKey(long peer) {
        try {
            return (int) GET_ALT_KEY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getMetaKey(long peer) {
        try {
            return (int) GET_META_KEY.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    // wkj_dom_MouseEvent_getButton returns int32_t; DOM button values are short, and JNI narrowed here too.
    static short getButton(long peer) {
        try {
            return (short) (int) GET_BUTTON.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getRelatedTarget(long peer) {
        try {
            return (long) GET_RELATED_TARGET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getOffsetX(long peer) {
        try {
            return (int) GET_OFFSET_X.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getOffsetY(long peer) {
        try {
            return (int) GET_OFFSET_Y.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getFromElement(long peer) {
        try {
            return (long) GET_FROM_ELEMENT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getToElement(long peer) {
        try {
            return (long) GET_TO_ELEMENT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void initMouseEvent(long peer, String type, boolean canBubble, boolean cancelable, long view, int detail,
            int screenX, int screenY, int clientX, int clientY, boolean ctrlKey, boolean altKey, boolean shiftKey,
            boolean metaKey, short button, long relatedTarget) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment typeSegment = WebKitNative.allocString(arena, type);
            try {
                INIT_MOUSE_EVENT.invokeExact(peer, typeSegment, WebKitNative.stringLength(type), canBubble ? 1 : 0,
                        cancelable ? 1 : 0, view, detail, screenX, screenY, clientX, clientY, ctrlKey ? 1 : 0,
                        altKey ? 1 : 0, shiftKey ? 1 : 0, metaKey ? 1 : 0, button, relatedTarget);
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }
}
