/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_NodeIterator_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link NodeIteratorImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class NodeIteratorNative {

    private static final MethodHandle DISPOSE = WebKitNative.downcall("wkj_dom_NodeIterator_dispose",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle GET_ROOT = WebKitNative.downcall("wkj_dom_NodeIterator_getRoot",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_WHAT_TO_SHOW = WebKitNative.downcall("wkj_dom_NodeIterator_getWhatToShow",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_FILTER = WebKitNative.downcall("wkj_dom_NodeIterator_getFilter",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_EXPAND_ENTITY_REFERENCES = WebKitNative.downcall(
            "wkj_dom_NodeIterator_getExpandEntityReferences", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_REFERENCE_NODE = WebKitNative.downcall(
            "wkj_dom_NodeIterator_getReferenceNode", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_POINTER_BEFORE_REFERENCE_NODE = WebKitNative.downcall(
            "wkj_dom_NodeIterator_getPointerBeforeReferenceNode", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle NEXT_NODE = WebKitNative.downcall("wkj_dom_NodeIterator_nextNode",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle PREVIOUS_NODE = WebKitNative.downcall("wkj_dom_NodeIterator_previousNode",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle DETACH = WebKitNative.downcall("wkj_dom_NodeIterator_detach",
            FunctionDescriptor.ofVoid(JAVA_LONG));

    private NodeIteratorNative() {
    }

    static void dispose(long peer) {
        try {
            DISPOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getRoot(long peer) {
        try {
            return (long) GET_ROOT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getWhatToShow(long peer) {
        try {
            return (int) GET_WHAT_TO_SHOW.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getFilter(long peer) {
        try {
            return (long) GET_FILTER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getExpandEntityReferences(long peer) {
        try {
            return (int) GET_EXPAND_ENTITY_REFERENCES.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getReferenceNode(long peer) {
        try {
            return (long) GET_REFERENCE_NODE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getPointerBeforeReferenceNode(long peer) {
        try {
            return (int) GET_POINTER_BEFORE_REFERENCE_NODE.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long nextNode(long peer) {
        try {
            return (long) NEXT_NODE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long previousNode(long peer) {
        try {
            return (long) PREVIOUS_NODE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void detach(long peer) {
        try {
            DETACH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }
}
