/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * FFM facade for the {@code wkj_dom_Range_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link RangeImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class RangeNative {

    private static final MethodHandle DISPOSE = WebKitNative.downcall("wkj_dom_Range_dispose",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle GET_START_CONTAINER = WebKitNative.downcall("wkj_dom_Range_getStartContainer",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_START_OFFSET = WebKitNative.downcall("wkj_dom_Range_getStartOffset",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_END_CONTAINER = WebKitNative.downcall("wkj_dom_Range_getEndContainer",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_END_OFFSET = WebKitNative.downcall("wkj_dom_Range_getEndOffset",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_COLLAPSED = WebKitNative.downcall("wkj_dom_Range_getCollapsed",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_COMMON_ANCESTOR_CONTAINER = WebKitNative.downcall(
            "wkj_dom_Range_getCommonAncestorContainer", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_TEXT = WebKitNative.downcall("wkj_dom_Range_getText",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle SET_START = WebKitNative.downcall("wkj_dom_Range_setStart",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_INT));
    private static final MethodHandle SET_END = WebKitNative.downcall("wkj_dom_Range_setEnd",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG, JAVA_INT));
    private static final MethodHandle SET_START_BEFORE = WebKitNative.downcall("wkj_dom_Range_setStartBefore",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_START_AFTER = WebKitNative.downcall("wkj_dom_Range_setStartAfter",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_END_BEFORE = WebKitNative.downcall("wkj_dom_Range_setEndBefore",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SET_END_AFTER = WebKitNative.downcall("wkj_dom_Range_setEndAfter",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle COLLAPSE = WebKitNative.downcall("wkj_dom_Range_collapse",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_INT));
    private static final MethodHandle SELECT_NODE = WebKitNative.downcall("wkj_dom_Range_selectNode",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SELECT_NODE_CONTENTS = WebKitNative.downcall("wkj_dom_Range_selectNodeContents",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle COMPARE_BOUNDARY_POINTS = WebKitNative.downcall(
            "wkj_dom_Range_compareBoundaryPoints", FunctionDescriptor.of(JAVA_SHORT, JAVA_LONG, JAVA_SHORT, JAVA_LONG));
    private static final MethodHandle DELETE_CONTENTS = WebKitNative.downcall("wkj_dom_Range_deleteContents",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle EXTRACT_CONTENTS = WebKitNative.downcall("wkj_dom_Range_extractContents",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle CLONE_CONTENTS = WebKitNative.downcall("wkj_dom_Range_cloneContents",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle INSERT_NODE = WebKitNative.downcall("wkj_dom_Range_insertNode",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SURROUND_CONTENTS = WebKitNative.downcall("wkj_dom_Range_surroundContents",
            FunctionDescriptor.ofVoid(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle CLONE_RANGE = WebKitNative.downcall("wkj_dom_Range_cloneRange",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle TO_STRING = WebKitNative.downcall("wkj_dom_Range_toString",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle DETACH = WebKitNative.downcall("wkj_dom_Range_detach",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle CREATE_CONTEXTUAL_FRAGMENT = WebKitNative.downcall(
            "wkj_dom_Range_createContextualFragment", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, ADDRESS, JAVA_INT));
    private static final MethodHandle COMPARE_NODE = WebKitNative.downcall("wkj_dom_Range_compareNode",
            FunctionDescriptor.of(JAVA_SHORT, JAVA_LONG, JAVA_LONG));
    private static final MethodHandle COMPARE_POINT = WebKitNative.downcall("wkj_dom_Range_comparePoint",
            FunctionDescriptor.of(JAVA_SHORT, JAVA_LONG, JAVA_LONG, JAVA_INT));
    private static final MethodHandle INTERSECTS_NODE = WebKitNative.downcall("wkj_dom_Range_intersectsNode",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG));
    private static final MethodHandle IS_POINT_IN_RANGE = WebKitNative.downcall("wkj_dom_Range_isPointInRange",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, JAVA_LONG, JAVA_INT));
    private static final MethodHandle EXPAND = WebKitNative.downcall("wkj_dom_Range_expand",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT));

    private RangeNative() {
    }

    static void dispose(long peer) {
        try {
            DISPOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getStartContainer(long peer) {
        try {
            return (long) GET_START_CONTAINER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getStartOffset(long peer) {
        try {
            return (int) GET_START_OFFSET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getEndContainer(long peer) {
        try {
            return (long) GET_END_CONTAINER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getEndOffset(long peer) {
        try {
            return (int) GET_END_OFFSET.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static boolean getCollapsed(long peer) {
        try {
            return (int) GET_COLLAPSED.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getCommonAncestorContainer(long peer) {
        try {
            return (long) GET_COMMON_ANCESTOR_CONTAINER.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String getText(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_TEXT.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_TEXT.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void setStart(long peer, long refNode, int offset) {
        try {
            SET_START.invokeExact(peer, refNode, offset);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void setEnd(long peer, long refNode, int offset) {
        try {
            SET_END.invokeExact(peer, refNode, offset);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void setStartBefore(long peer, long refNode) {
        try {
            SET_START_BEFORE.invokeExact(peer, refNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void setStartAfter(long peer, long refNode) {
        try {
            SET_START_AFTER.invokeExact(peer, refNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void setEndBefore(long peer, long refNode) {
        try {
            SET_END_BEFORE.invokeExact(peer, refNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void setEndAfter(long peer, long refNode) {
        try {
            SET_END_AFTER.invokeExact(peer, refNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void collapse(long peer, boolean toStart) {
        try {
            COLLAPSE.invokeExact(peer, toStart ? 1 : 0);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void selectNode(long peer, long refNode) {
        try {
            SELECT_NODE.invokeExact(peer, refNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void selectNodeContents(long peer, long refNode) {
        try {
            SELECT_NODE_CONTENTS.invokeExact(peer, refNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static short compareBoundaryPoints(long peer, short how, long sourceRange) {
        short result;
        try {
            result = (short) COMPARE_BOUNDARY_POINTS.invokeExact(peer, how, sourceRange);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static void deleteContents(long peer) {
        try {
            DELETE_CONTENTS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static long extractContents(long peer) {
        long result;
        try {
            result = (long) EXTRACT_CONTENTS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static long cloneContents(long peer) {
        long result;
        try {
            result = (long) CLONE_CONTENTS.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static void insertNode(long peer, long newNode) {
        try {
            INSERT_NODE.invokeExact(peer, newNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static void surroundContents(long peer, long newParent) {
        try {
            SURROUND_CONTENTS.invokeExact(peer, newParent);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
    }

    static long cloneRange(long peer) {
        try {
            return (long) CLONE_RANGE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static String toString(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) TO_STRING.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) TO_STRING.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static void detach(long peer) {
        try {
            DETACH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long createContextualFragment(long peer, String html) {
        long result;
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment htmlSegment = WebKitNative.allocString(arena, html);
            try {
                result = (long) CREATE_CONTEXTUAL_FRAGMENT.invokeExact(peer, htmlSegment,
                        WebKitNative.stringLength(html));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
        return result;
    }

    static short compareNode(long peer, long refNode) {
        short result;
        try {
            result = (short) COMPARE_NODE.invokeExact(peer, refNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static short comparePoint(long peer, long refNode, int offset) {
        short result;
        try {
            result = (short) COMPARE_POINT.invokeExact(peer, refNode, offset);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static boolean intersectsNode(long peer, long refNode) {
        int result;
        try {
            result = (int) INTERSECTS_NODE.invokeExact(peer, refNode);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result != 0;
    }

    static boolean isPointInRange(long peer, long refNode, int offset) {
        int result;
        try {
            result = (int) IS_POINT_IN_RANGE.invokeExact(peer, refNode, offset);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result != 0;
    }

    static void expand(long peer, String unit) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment unitSegment = WebKitNative.allocString(arena, unit);
            try {
                EXPAND.invokeExact(peer, unitSegment, WebKitNative.stringLength(unit));
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
        WebKitNative.checkException();
    }
}
