/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.FunctionDescriptor;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_Rect_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link RectImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class RectNative {

    private static final MethodHandle DISPOSE = WebKitNative.downcall("wkj_dom_Rect_dispose",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle GET_TOP = WebKitNative.downcall("wkj_dom_Rect_getTop",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_RIGHT = WebKitNative.downcall("wkj_dom_Rect_getRight",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_BOTTOM = WebKitNative.downcall("wkj_dom_Rect_getBottom",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_LEFT = WebKitNative.downcall("wkj_dom_Rect_getLeft",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));

    private RectNative() {
    }

    static void dispose(long peer) {
        try {
            DISPOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getTop(long peer) {
        try {
            return (long) GET_TOP.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getRight(long peer) {
        try {
            return (long) GET_RIGHT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getBottom(long peer) {
        try {
            return (long) GET_BOTTOM.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static long getLeft(long peer) {
        try {
            return (long) GET_LEFT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }
}
