/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;

/**
 * FFM facade for the {@code wkj_dom_UIEvent_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link UIEventImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class UIEventNative {

    private static final MethodHandle GET_VIEW = WebKitNative.downcall("wkj_dom_UIEvent_getView",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_DETAIL = WebKitNative.downcall("wkj_dom_UIEvent_getDetail",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_KEY_CODE = WebKitNative.downcall("wkj_dom_UIEvent_getKeyCode",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_CHAR_CODE = WebKitNative.downcall("wkj_dom_UIEvent_getCharCode",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_LAYER_X = WebKitNative.downcall("wkj_dom_UIEvent_getLayerX",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_LAYER_Y = WebKitNative.downcall("wkj_dom_UIEvent_getLayerY",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_PAGE_X = WebKitNative.downcall("wkj_dom_UIEvent_getPageX",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_PAGE_Y = WebKitNative.downcall("wkj_dom_UIEvent_getPageY",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_WHICH = WebKitNative.downcall("wkj_dom_UIEvent_getWhich",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle INIT_UI_EVENT = WebKitNative.downcall("wkj_dom_UIEvent_initUIEvent",
            FunctionDescriptor.ofVoid(JAVA_LONG, ADDRESS, JAVA_INT, JAVA_INT, JAVA_INT, JAVA_LONG, JAVA_INT));

    private UIEventNative() {
    }

    static long getView(long peer) {
        try {
            return (long) GET_VIEW.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getDetail(long peer) {
        try {
            return (int) GET_DETAIL.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getKeyCode(long peer) {
        try {
            return (int) GET_KEY_CODE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getCharCode(long peer) {
        try {
            return (int) GET_CHAR_CODE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getLayerX(long peer) {
        try {
            return (int) GET_LAYER_X.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getLayerY(long peer) {
        try {
            return (int) GET_LAYER_Y.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getPageX(long peer) {
        try {
            return (int) GET_PAGE_X.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getPageY(long peer) {
        try {
            return (int) GET_PAGE_Y.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getWhich(long peer) {
        try {
            return (int) GET_WHICH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static void initUIEvent(long peer, String type, boolean canBubble, boolean cancelable, long view, int detail) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment typeSegment = WebKitNative.allocString(arena, type);
            try {
                INIT_UI_EVENT.invokeExact(peer, typeSegment, WebKitNative.stringLength(type), canBubble ? 1 : 0,
                        cancelable ? 1 : 0, view, detail);
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
        }
    }
}
