/*
 * Copyright (c) 2026, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package com.sun.webkit.dom;

import com.sun.webkit.WebKitNative;
import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.MemorySegment;
import java.lang.invoke.MethodHandle;
import static java.lang.foreign.ValueLayout.ADDRESS;
import static java.lang.foreign.ValueLayout.JAVA_CHAR;
import static java.lang.foreign.ValueLayout.JAVA_DOUBLE;
import static java.lang.foreign.ValueLayout.JAVA_INT;
import static java.lang.foreign.ValueLayout.JAVA_LONG;
import static java.lang.foreign.ValueLayout.JAVA_SHORT;

/**
 * FFM facade for the {@code wkj_dom_XPathResult_*} functions of the {@code jfxwebkit} C ABI, used by
 * {@link XPathResultImpl}. One facade per DOM type keeps symbol resolution lazy: the handles below are
 * bound the first time this type is touched, not the first time any DOM object is.
 * <p>
 * Generated by {@code buildtools/ffm-web/dom-java-to-ffm.pl} from
 * {@code buildtools/ffm-web/dom-abi.tsv}. Do not edit; regenerate.
 * <p>
 * These downcalls deliberately do not use {@code Linker.Option.critical(true)}, and no downcall in
 * this layer may. A DOM read or mutation can synchronously run script and fire event listeners,
 * which upcall into Java, and a critical downcall forbids upcalls. The gain would be one avoided
 * copy of a string; the cost would be an intermittent crash.
 *
 * @see com.sun.webkit.WebKitNative
 */
final class XPathResultNative {

    private static final MethodHandle DISPOSE = WebKitNative.downcall("wkj_dom_XPathResult_dispose",
            FunctionDescriptor.ofVoid(JAVA_LONG));
    private static final MethodHandle GET_RESULT_TYPE = WebKitNative.downcall("wkj_dom_XPathResult_getResultType",
            FunctionDescriptor.of(JAVA_SHORT, JAVA_LONG));
    private static final MethodHandle GET_NUMBER_VALUE = WebKitNative.downcall("wkj_dom_XPathResult_getNumberValue",
            FunctionDescriptor.of(JAVA_DOUBLE, JAVA_LONG));
    private static final MethodHandle GET_STRING_VALUE = WebKitNative.downcall("wkj_dom_XPathResult_getStringValue",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG, ADDRESS, JAVA_INT, ADDRESS));
    private static final MethodHandle GET_BOOLEAN_VALUE = WebKitNative.downcall("wkj_dom_XPathResult_getBooleanValue",
            FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SINGLE_NODE_VALUE = WebKitNative.downcall(
            "wkj_dom_XPathResult_getSingleNodeValue", FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle GET_INVALID_ITERATOR_STATE = WebKitNative.downcall(
            "wkj_dom_XPathResult_getInvalidIteratorState", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle GET_SNAPSHOT_LENGTH = WebKitNative.downcall(
            "wkj_dom_XPathResult_getSnapshotLength", FunctionDescriptor.of(JAVA_INT, JAVA_LONG));
    private static final MethodHandle ITERATE_NEXT = WebKitNative.downcall("wkj_dom_XPathResult_iterateNext",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG));
    private static final MethodHandle SNAPSHOT_ITEM = WebKitNative.downcall("wkj_dom_XPathResult_snapshotItem",
            FunctionDescriptor.of(JAVA_LONG, JAVA_LONG, JAVA_INT));

    private XPathResultNative() {
    }

    static void dispose(long peer) {
        try {
            DISPOSE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static short getResultType(long peer) {
        try {
            return (short) GET_RESULT_TYPE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static double getNumberValue(long peer) {
        double result;
        try {
            result = (double) GET_NUMBER_VALUE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static String getStringValue(long peer) {
        try (Arena arena = Arena.ofConfined()) {
            MemorySegment resultLength = arena.allocate(JAVA_INT);
            MemorySegment resultBuffer = arena.allocate(JAVA_CHAR, DOMStringCodec.CAPACITY);
            int status;
            try {
                status = (int) GET_STRING_VALUE.invokeExact(peer, resultBuffer, DOMStringCodec.CAPACITY, resultLength);
                if (status == DOMStringCodec.OVERFLOW) {
                    int required = resultLength.get(JAVA_INT, 0);
                    resultBuffer = arena.allocate(JAVA_CHAR, required);
                    status = (int) GET_STRING_VALUE.invokeExact(peer, resultBuffer, required, resultLength);
                }
            } catch (Throwable t) {
                throw new AssertionError(t);
            }
            WebKitNative.checkException();
            return DOMStringCodec.decode(status, resultBuffer, resultLength);
        }
    }

    static boolean getBooleanValue(long peer) {
        int result;
        try {
            result = (int) GET_BOOLEAN_VALUE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result != 0;
    }

    static long getSingleNodeValue(long peer) {
        long result;
        try {
            result = (long) GET_SINGLE_NODE_VALUE.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static boolean getInvalidIteratorState(long peer) {
        try {
            return (int) GET_INVALID_ITERATOR_STATE.invokeExact(peer) != 0;
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
    }

    static int getSnapshotLength(long peer) {
        int result;
        try {
            result = (int) GET_SNAPSHOT_LENGTH.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static long iterateNext(long peer) {
        long result;
        try {
            result = (long) ITERATE_NEXT.invokeExact(peer);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }

    static long snapshotItem(long peer, int index) {
        long result;
        try {
            result = (long) SNAPSHOT_ITEM.invokeExact(peer, index);
        } catch (Throwable t) {
            throw new AssertionError(t);
        }
        WebKitNative.checkException();
        return result;
    }
}
