/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.transform;

/**
Builder class for javafx.scene.transform.Scale
@see javafx.scene.transform.Scale
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class ScaleBuilder<B extends javafx.scene.transform.ScaleBuilder<B>> implements javafx.util.Builder<javafx.scene.transform.Scale> {
    protected ScaleBuilder() {
    }
    
    /** Creates a new instance of ScaleBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.transform.ScaleBuilder<?> create() {
        return new javafx.scene.transform.ScaleBuilder();
    }
    
    private int __set;
    public void applyTo(javafx.scene.transform.Scale x) {
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setPivotX(this.pivotX);
        if ((set & (1 << 1)) != 0) x.setPivotY(this.pivotY);
        if ((set & (1 << 2)) != 0) x.setPivotZ(this.pivotZ);
        if ((set & (1 << 3)) != 0) x.setX(this.x);
        if ((set & (1 << 4)) != 0) x.setY(this.y);
        if ((set & (1 << 5)) != 0) x.setZ(this.z);
    }
    
    private double pivotX;
    /**
    Set the value of the {@link javafx.scene.transform.Scale#getPivotX() pivotX} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B pivotX(double x) {
        this.pivotX = x;
        __set |= 1 << 0;
        return (B) this;
    }
    
    private double pivotY;
    /**
    Set the value of the {@link javafx.scene.transform.Scale#getPivotY() pivotY} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B pivotY(double x) {
        this.pivotY = x;
        __set |= 1 << 1;
        return (B) this;
    }
    
    private double pivotZ;
    /**
    Set the value of the {@link javafx.scene.transform.Scale#getPivotZ() pivotZ} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B pivotZ(double x) {
        this.pivotZ = x;
        __set |= 1 << 2;
        return (B) this;
    }
    
    private double x;
    /**
    Set the value of the {@link javafx.scene.transform.Scale#getX() x} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B x(double x) {
        this.x = x;
        __set |= 1 << 3;
        return (B) this;
    }
    
    private double y;
    /**
    Set the value of the {@link javafx.scene.transform.Scale#getY() y} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B y(double x) {
        this.y = x;
        __set |= 1 << 4;
        return (B) this;
    }
    
    private double z;
    /**
    Set the value of the {@link javafx.scene.transform.Scale#getZ() z} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B z(double x) {
        this.z = x;
        __set |= 1 << 5;
        return (B) this;
    }
    
    /**
    Make an instance of {@link javafx.scene.transform.Scale} based on the properties set on this builder.
    */
    public javafx.scene.transform.Scale build() {
        javafx.scene.transform.Scale x = new javafx.scene.transform.Scale();
        applyTo(x);
        return x;
    }
}
