if (WIN32 OR CYGWIN)
    file(TO_CMAKE_PATH "${WEBKIT_OUTPUTDIR}" WEBKIT_OUTPUTDIR)
    file(TO_CMAKE_PATH "${RT_BUILD_ROOT}" RT_BUILD_ROOT)

    message(STATUS "WEBKIT_OUTPUTDIR = ${WEBKIT_OUTPUTDIR}")
    message(STATUS "RT_BUILD_ROOT = ${RT_BUILD_ROOT}")

    #Define very short root paths
    set(SHORT_SRC_ROOT "${RT_BUILD_ROOT}/ws")
    set(SHORT_BIN_ROOT "${RT_BUILD_ROOT}/wb")

    #Function to create Junctions (handles Cygwin path conversion)
    macro(create_short_junction TARGET_PATH JUNCTION_PATH)
        if (CYGWIN)
            execute_process(COMMAND cygpath -w "${TARGET_PATH}" OUTPUT_VARIABLE SRC_W OUTPUT_STRIP_TRAILING_WHITESPACE)
            execute_process(COMMAND cygpath -w "${JUNCTION_PATH}" OUTPUT_VARIABLE DST_W OUTPUT_STRIP_TRAILING_WHITESPACE)
        else()
            file(TO_NATIVE_PATH "${TARGET_PATH}" SRC_W)
            file(TO_NATIVE_PATH "${JUNCTION_PATH}" DST_W)
        endif()

        execute_process(COMMAND cmd /c if not exist "${DST_W}" mklink /J "${DST_W}" "${SRC_W}")
    endmacro()

    # Create the short paths
    create_short_junction("${CMAKE_SOURCE_DIR}" "${SHORT_SRC_ROOT}")
    create_short_junction("${CMAKE_BINARY_DIR}" "${SHORT_BIN_ROOT}")

    # Assign variables using the short paths
    set(BMALLOC_DIR           "${SHORT_SRC_ROOT}/Source/bmalloc")
    set(WTF_DIR               "${SHORT_SRC_ROOT}/Source/WTF")
    set(JAVASCRIPTCORE_DIR    "${SHORT_SRC_ROOT}/Source/JavaScriptCore")
    set(WEBCORE_DIR           "${SHORT_SRC_ROOT}/Source/WebCore")
    set(PAL_DIR               "${SHORT_SRC_ROOT}/Source/WebCore/PAL")
    set(WEBKITLEGACY_DIR      "${SHORT_SRC_ROOT}/Source/WebKitLegacy")
    set(WEBKIT_DIR            "${SHORT_SRC_ROOT}/Source/WebKit")
    set(THIRDPARTY_DIR        "${SHORT_SRC_ROOT}/Source/ThirdParty")
    set(TOOLS_DIR             "${SHORT_SRC_ROOT}/Tools")
    set(WEBDRIVER_DIR         "${SHORT_SRC_ROOT}/Source/WebDriver")
    set(WEBINSPECTORUI_DIR    "${SHORT_SRC_ROOT}/Source/WebInspectorUI")

    # Derived Sources (using SHORT_BIN_ROOT)
    set(WTF_DERIVED_SOURCES_DIR            "${SHORT_BIN_ROOT}/WTF/DerivedSources")
    set(JavaScriptCore_DERIVED_SOURCES_DIR "${SHORT_BIN_ROOT}/JavaScriptCore/DerivedSources")
    set(PAL_DERIVED_SOURCES_DIR            "${SHORT_BIN_ROOT}/PAL/DerivedSources")
    set(WebCore_DERIVED_SOURCES_DIR        "${SHORT_BIN_ROOT}/WebCore/DerivedSources")
    set(WebDriver_DERIVED_SOURCES_DIR      "${SHORT_BIN_ROOT}/WebDriver/DerivedSources")
    set(WebKitLegacy_DERIVED_SOURCES_DIR   "${SHORT_BIN_ROOT}/WebKitLegacy/DerivedSources")
    set(WebKit_DERIVED_SOURCES_DIR         "${SHORT_BIN_ROOT}/WebKit/DerivedSources")
    set(WebInspectorUI_DERIVED_SOURCES_DIR "${SHORT_BIN_ROOT}/WebInspectorUI/DerivedSources")
    set(MiniBrowser_DERIVED_SOURCES_DIR    "${SHORT_BIN_ROOT}/MiniBrowser/DerivedSources")
    set(TestRunnerShared_DERIVED_SOURCES_DIR "${SHORT_BIN_ROOT}/TestRunnerShared/DerivedSources")
    set(DumpRenderTree_DERIVED_SOURCES_DIR "${SHORT_BIN_ROOT}/DumpRenderTree/DerivedSources")
    set(WebKitTestRunner_DERIVED_SOURCES_DIR "${SHORT_BIN_ROOT}/WebKitTestRunner/DerivedSources")

    # Framework Headers
    set(bmalloc_FRAMEWORK_HEADERS_DIR      "${SHORT_BIN_ROOT}/bmalloc/Headers")
    set(ANGLE_FRAMEWORK_HEADERS_DIR        "${SHORT_BIN_ROOT}/ANGLE/Headers")
    set(Skia_FRAMEWORK_HEADERS_DIR         "${SHORT_BIN_ROOT}/Skia/Headers")
    set(WTF_FRAMEWORK_HEADERS_DIR          "${SHORT_BIN_ROOT}/WTF/Headers")
    set(JavaScriptCore_FRAMEWORK_HEADERS_DIR "${SHORT_BIN_ROOT}/JavaScriptCore/Headers")
    set(JavaScriptCore_PRIVATE_FRAMEWORK_HEADERS_DIR "${SHORT_BIN_ROOT}/JavaScriptCore/PrivateHeaders")
    set(PAL_FRAMEWORK_HEADERS_DIR          "${SHORT_BIN_ROOT}/PAL/Headers")
    set(WebCore_PRIVATE_FRAMEWORK_HEADERS_DIR "${SHORT_BIN_ROOT}/WebCore/PrivateHeaders")
    set(WebKitLegacy_FRAMEWORK_HEADERS_DIR "${SHORT_BIN_ROOT}/WebKitLegacy/Headers")
    set(WebKit_FRAMEWORK_HEADERS_DIR       "${SHORT_BIN_ROOT}/WebKit/Headers")
    set(WebKit_PRIVATE_FRAMEWORK_HEADERS_DIR "${SHORT_BIN_ROOT}/WebKit/PrivateHeaders")

    # Scripts
    set(WTF_SCRIPTS_DIR                    "${SHORT_BIN_ROOT}/WTF/Scripts")
    set(JavaScriptCore_SCRIPTS_DIR         "${SHORT_BIN_ROOT}/JavaScriptCore/Scripts")

else()
    # ORIGINAL LOGIC FOR NON-WINDOWS
    if (NOT BMALLOC_DIR)
        set(BMALLOC_DIR "${CMAKE_SOURCE_DIR}/Source/bmalloc")
    endif ()
    if (NOT WTF_DIR)
        set(WTF_DIR "${CMAKE_SOURCE_DIR}/Source/WTF")
    endif ()
    if (NOT JAVASCRIPTCORE_DIR)
        set(JAVASCRIPTCORE_DIR "${CMAKE_SOURCE_DIR}/Source/JavaScriptCore")
    endif ()
    if (NOT WEBCORE_DIR)
        set(WEBCORE_DIR "${CMAKE_SOURCE_DIR}/Source/WebCore")
    endif ()
    if (NOT PAL_DIR)
        set(PAL_DIR "${CMAKE_SOURCE_DIR}/Source/WebCore/PAL")
    endif ()
    if (NOT WEBKITLEGACY_DIR)
        set(WEBKITLEGACY_DIR "${CMAKE_SOURCE_DIR}/Source/WebKitLegacy")
    endif ()
    if (NOT WEBKIT_DIR)
        set(WEBKIT_DIR "${CMAKE_SOURCE_DIR}/Source/WebKit")
    endif ()
    if (NOT THIRDPARTY_DIR)
        set(THIRDPARTY_DIR "${CMAKE_SOURCE_DIR}/Source/ThirdParty")
    endif ()
    if (NOT TOOLS_DIR)
        set(TOOLS_DIR "${CMAKE_SOURCE_DIR}/Tools")
    endif ()
    if (NOT WEBDRIVER_DIR)
        set(WEBDRIVER_DIR "${CMAKE_SOURCE_DIR}/Source/WebDriver")
    endif ()
    if (NOT WEBINSPECTORUI_DIR)
        set(WEBINSPECTORUI_DIR "${CMAKE_SOURCE_DIR}/Source/WebInspectorUI")
    endif ()

    set(WTF_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WTF/DerivedSources")
    set(JavaScriptCore_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/JavaScriptCore/DerivedSources")
    set(PAL_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/PAL/DerivedSources")
    set(WebCore_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WebCore/DerivedSources")
    set(WebDriver_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WebDriver/DerivedSources")
    set(WebKitLegacy_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WebKitLegacy/DerivedSources")
    set(WebKit_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WebKit/DerivedSources")
    set(WebInspectorUI_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WebInspectorUI/DerivedSources")
    set(MiniBrowser_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/MiniBrowser/DerivedSources")
    set(TestRunnerShared_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/TestRunnerShared/DerivedSources")
    set(DumpRenderTree_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/DumpRenderTree/DerivedSources")
    set(WebKitTestRunner_DERIVED_SOURCES_DIR "${CMAKE_BINARY_DIR}/WebKitTestRunner/DerivedSources")

    set(bmalloc_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/bmalloc/Headers")
    set(ANGLE_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/ANGLE/Headers")
    set(Skia_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/Skia/Headers")
    set(WTF_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/WTF/Headers")
    set(JavaScriptCore_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/JavaScriptCore/Headers")
    set(JavaScriptCore_PRIVATE_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/JavaScriptCore/PrivateHeaders")
    set(PAL_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/PAL/Headers")
    set(WebCore_PRIVATE_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/WebCore/PrivateHeaders")
    set(WebKitLegacy_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/WebKitLegacy/Headers")
    set(WebKit_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/WebKit/Headers")
    set(WebKit_PRIVATE_FRAMEWORK_HEADERS_DIR "${CMAKE_BINARY_DIR}/WebKit/PrivateHeaders")

    set(WTF_SCRIPTS_DIR "${CMAKE_BINARY_DIR}/WTF/Scripts")
    set(JavaScriptCore_SCRIPTS_DIR "${CMAKE_BINARY_DIR}/JavaScriptCore/Scripts")
endif ()
