/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.layout;

/**
Builder class for javafx.scene.layout.AnchorPane
@see javafx.scene.layout.AnchorPane
@deprecated This class is deprecated and will be removed in the next version
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class AnchorPaneBuilder<B extends javafx.scene.layout.AnchorPaneBuilder<B>> extends javafx.scene.layout.PaneBuilder<B> {
    protected AnchorPaneBuilder() {
    }
    
    /** Creates a new instance of AnchorPaneBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.layout.AnchorPaneBuilder<?> create() {
        return new javafx.scene.layout.AnchorPaneBuilder();
    }
    
    /**
    Make an instance of {@link javafx.scene.layout.AnchorPane} based on the properties set on this builder.
    */
    public javafx.scene.layout.AnchorPane build() {
        javafx.scene.layout.AnchorPane x = new javafx.scene.layout.AnchorPane();
        applyTo(x);
        return x;
    }
}
