/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.shape;

/**
Builder class for javafx.scene.shape.CubicCurveTo
@see javafx.scene.shape.CubicCurveTo
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class CubicCurveToBuilder<B extends javafx.scene.shape.CubicCurveToBuilder<B>> extends javafx.scene.shape.PathElementBuilder<B> implements javafx.util.Builder<javafx.scene.shape.CubicCurveTo> {
    protected CubicCurveToBuilder() {
    }
    
    /** Creates a new instance of CubicCurveToBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.shape.CubicCurveToBuilder<?> create() {
        return new javafx.scene.shape.CubicCurveToBuilder();
    }
    
    private int __set;
    public void applyTo(javafx.scene.shape.CubicCurveTo x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setControlX1(this.controlX1);
        if ((set & (1 << 1)) != 0) x.setControlX2(this.controlX2);
        if ((set & (1 << 2)) != 0) x.setControlY1(this.controlY1);
        if ((set & (1 << 3)) != 0) x.setControlY2(this.controlY2);
        if ((set & (1 << 4)) != 0) x.setX(this.x);
        if ((set & (1 << 5)) != 0) x.setY(this.y);
    }
    
    private double controlX1;
    /**
    Set the value of the {@link javafx.scene.shape.CubicCurveTo#getControlX1() controlX1} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B controlX1(double x) {
        this.controlX1 = x;
        __set |= 1 << 0;
        return (B) this;
    }
    
    private double controlX2;
    /**
    Set the value of the {@link javafx.scene.shape.CubicCurveTo#getControlX2() controlX2} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B controlX2(double x) {
        this.controlX2 = x;
        __set |= 1 << 1;
        return (B) this;
    }
    
    private double controlY1;
    /**
    Set the value of the {@link javafx.scene.shape.CubicCurveTo#getControlY1() controlY1} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B controlY1(double x) {
        this.controlY1 = x;
        __set |= 1 << 2;
        return (B) this;
    }
    
    private double controlY2;
    /**
    Set the value of the {@link javafx.scene.shape.CubicCurveTo#getControlY2() controlY2} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B controlY2(double x) {
        this.controlY2 = x;
        __set |= 1 << 3;
        return (B) this;
    }
    
    private double x;
    /**
    Set the value of the {@link javafx.scene.shape.CubicCurveTo#getX() x} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B x(double x) {
        this.x = x;
        __set |= 1 << 4;
        return (B) this;
    }
    
    private double y;
    /**
    Set the value of the {@link javafx.scene.shape.CubicCurveTo#getY() y} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B y(double x) {
        this.y = x;
        __set |= 1 << 5;
        return (B) this;
    }
    
    /**
    Make an instance of {@link javafx.scene.shape.CubicCurveTo} based on the properties set on this builder.
    */
    public javafx.scene.shape.CubicCurveTo build() {
        javafx.scene.shape.CubicCurveTo x = new javafx.scene.shape.CubicCurveTo();
        applyTo(x);
        return x;
    }
}
