// Automatically generated by CodeGeneratorJava.pm. Do not edit.

package com.sun.webkit.dom;

import org.w3c.dom.css.CSSValue;
import org.w3c.dom.css.CSSValueList;

public class CSSValueListImpl extends CSSValueImpl implements CSSValueList {
    CSSValueListImpl(long peer) {
        super(peer);
    }

    static CSSValueList getImpl(long peer) {
        return (CSSValueList)create(peer);
    }


//attributes
    public int getLength() {
        return getLengthImpl(getPeer());
    }
    native static int getLengthImpl(long peer);


//functions
    public CSSValue item(int index)
    {
        return CSSValueImpl.getImpl(itemImpl(getPeer()
            , index));
    }
    native static long itemImpl(long peer
        , int index);


}

