/* 
 * Copyright (c) 2011, 2014, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.ContextMenu
@see javafx.scene.control.ContextMenu
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class ContextMenuBuilder<B extends javafx.scene.control.ContextMenuBuilder<B>> extends javafx.scene.control.PopupControlBuilder<B> {
    protected ContextMenuBuilder() {
    }
    
    /** Creates a new instance of ContextMenuBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.ContextMenuBuilder<?> create() {
        return new javafx.scene.control.ContextMenuBuilder();
    }
    
    private int __set;
    public void applyTo(javafx.scene.control.ContextMenu x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setImpl_showRelativeToWindow(this.impl_showRelativeToWindow);
        if ((set & (1 << 1)) != 0) x.getItems().addAll(this.items);
        if ((set & (1 << 2)) != 0) x.setOnAction(this.onAction);
    }
    
    private boolean impl_showRelativeToWindow;
    /**
    Set the value of the {@link javafx.scene.control.ContextMenu#isImpl_showRelativeToWindow() impl_showRelativeToWindow} property for the instance constructed by this builder.
    @treatAsPrivate
    @deprecated This is an internal API that is not intended for use and will be removed in the next version
    */
    @SuppressWarnings("unchecked") @Deprecated
    public B impl_showRelativeToWindow(boolean x) {
        this.impl_showRelativeToWindow = x;
        __set |= 1 << 0;
        return (B) this;
    }
    
    private java.util.Collection<? extends javafx.scene.control.MenuItem> items;
    /**
    Add the given items to the List of items in the {@link javafx.scene.control.ContextMenu#getItems() items} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B items(java.util.Collection<? extends javafx.scene.control.MenuItem> x) {
        this.items = x;
        __set |= 1 << 1;
        return (B) this;
    }
    
    /**
    Add the given items to the List of items in the {@link javafx.scene.control.ContextMenu#getItems() items} property for the instance constructed by this builder.
    */
    public B items(javafx.scene.control.MenuItem... x) {
        return items(java.util.Arrays.asList(x));
    }
    
    private javafx.event.EventHandler<javafx.event.ActionEvent> onAction;
    /**
    Set the value of the {@link javafx.scene.control.ContextMenu#getOnAction() onAction} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B onAction(javafx.event.EventHandler<javafx.event.ActionEvent> x) {
        this.onAction = x;
        __set |= 1 << 2;
        return (B) this;
    }
    
    /**
    Make an instance of {@link javafx.scene.control.ContextMenu} based on the properties set on this builder.
    */
    public javafx.scene.control.ContextMenu build() {
        javafx.scene.control.ContextMenu x = new javafx.scene.control.ContextMenu();
        applyTo(x);
        return x;
    }
}
