/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.Label
@see javafx.scene.control.Label
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class LabelBuilder<B extends javafx.scene.control.LabelBuilder<B>> extends javafx.scene.control.LabeledBuilder<B> implements javafx.util.Builder<javafx.scene.control.Label> {
    protected LabelBuilder() {
    }
    
    /** Creates a new instance of LabelBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.LabelBuilder<?> create() {
        return new javafx.scene.control.LabelBuilder();
    }
    
    private boolean __set;
    public void applyTo(javafx.scene.control.Label x) {
        super.applyTo(x);
        if (__set) x.setLabelFor(this.labelFor);
    }
    
    private javafx.scene.Node labelFor;
    /**
    Set the value of the {@link javafx.scene.control.Label#getLabelFor() labelFor} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B labelFor(javafx.scene.Node x) {
        this.labelFor = x;
        __set = true;
        return (B) this;
    }
    
    /**
    Make an instance of {@link javafx.scene.control.Label} based on the properties set on this builder.
    */
    public javafx.scene.control.Label build() {
        javafx.scene.control.Label x = new javafx.scene.control.Label();
        applyTo(x);
        return x;
    }
}
