/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.TitledPane
@see javafx.scene.control.TitledPane
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class TitledPaneBuilder<B extends javafx.scene.control.TitledPaneBuilder<B>> extends javafx.scene.control.LabeledBuilder<B> implements javafx.util.Builder<javafx.scene.control.TitledPane> {
    protected TitledPaneBuilder() {
    }
    
    /** Creates a new instance of TitledPaneBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.TitledPaneBuilder<?> create() {
        return new javafx.scene.control.TitledPaneBuilder();
    }
    
    private int __set;
    public void applyTo(javafx.scene.control.TitledPane x) {
        super.applyTo(x);
        int set = __set;
        if ((set & (1 << 0)) != 0) x.setAnimated(this.animated);
        if ((set & (1 << 1)) != 0) x.setCollapsible(this.collapsible);
        if ((set & (1 << 2)) != 0) x.setContent(this.content);
        if ((set & (1 << 3)) != 0) x.setExpanded(this.expanded);
    }
    
    private boolean animated;
    /**
    Set the value of the {@link javafx.scene.control.TitledPane#isAnimated() animated} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B animated(boolean x) {
        this.animated = x;
        __set |= 1 << 0;
        return (B) this;
    }
    
    private boolean collapsible;
    /**
    Set the value of the {@link javafx.scene.control.TitledPane#isCollapsible() collapsible} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B collapsible(boolean x) {
        this.collapsible = x;
        __set |= 1 << 1;
        return (B) this;
    }
    
    private javafx.scene.Node content;
    /**
    Set the value of the {@link javafx.scene.control.TitledPane#getContent() content} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B content(javafx.scene.Node x) {
        this.content = x;
        __set |= 1 << 2;
        return (B) this;
    }
    
    private boolean expanded;
    /**
    Set the value of the {@link javafx.scene.control.TitledPane#isExpanded() expanded} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B expanded(boolean x) {
        this.expanded = x;
        __set |= 1 << 3;
        return (B) this;
    }
    
    /**
    Make an instance of {@link javafx.scene.control.TitledPane} based on the properties set on this builder.
    */
    public javafx.scene.control.TitledPane build() {
        javafx.scene.control.TitledPane x = new javafx.scene.control.TitledPane();
        applyTo(x);
        return x;
    }
}
