/* 
 * Copyright (c) 2011, 2013, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */

package javafx.scene.control;

/**
Builder class for javafx.scene.control.ToggleGroup
@see javafx.scene.control.ToggleGroup
@deprecated This class is deprecated and will be removed in the next version
* @since JavaFX 2.0
*/
@javax.annotation.Generated("Generated by javafx.builder.processor.BuilderProcessor")
@Deprecated
public class ToggleGroupBuilder<B extends javafx.scene.control.ToggleGroupBuilder<B>> implements javafx.util.Builder<javafx.scene.control.ToggleGroup> {
    protected ToggleGroupBuilder() {
    }
    
    /** Creates a new instance of ToggleGroupBuilder. */
    @SuppressWarnings({"deprecation", "rawtypes", "unchecked"})
    public static javafx.scene.control.ToggleGroupBuilder<?> create() {
        return new javafx.scene.control.ToggleGroupBuilder();
    }
    
    private boolean __set;
    public void applyTo(javafx.scene.control.ToggleGroup x) {
        if (__set) x.getToggles().addAll(this.toggles);
    }
    
    private java.util.Collection<? extends javafx.scene.control.Toggle> toggles;
    /**
    Add the given items to the List of items in the {@link javafx.scene.control.ToggleGroup#getToggles() toggles} property for the instance constructed by this builder.
    */
    @SuppressWarnings("unchecked")
    public B toggles(java.util.Collection<? extends javafx.scene.control.Toggle> x) {
        this.toggles = x;
        __set = true;
        return (B) this;
    }
    
    /**
    Add the given items to the List of items in the {@link javafx.scene.control.ToggleGroup#getToggles() toggles} property for the instance constructed by this builder.
    */
    public B toggles(javafx.scene.control.Toggle... x) {
        return toggles(java.util.Arrays.asList(x));
    }
    
    /**
    Make an instance of {@link javafx.scene.control.ToggleGroup} based on the properties set on this builder.
    */
    public javafx.scene.control.ToggleGroup build() {
        javafx.scene.control.ToggleGroup x = new javafx.scene.control.ToggleGroup();
        applyTo(x);
        return x;
    }
}
